//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.19 at 02:10:39 PM CEST 
//


package pl.gov.mf.ksef.schema.gtw.svc.batch.types._2021._10._01._0001;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PackageType" type="{http://ksef.mf.gov.pl/schema/gtw/svc/batch/types/2021/10/01/0001}PackageTypeType"/>
 *         &lt;element name="CompressionType" type="{http://ksef.mf.gov.pl/schema/gtw/svc/batch/types/2021/10/01/0001}CompressionTypeType"/>
 *         &lt;element name="Value" type="{http://ksef.mf.gov.pl/schema/gtw/svc/batch/types/2021/10/01/0001}PackageNameType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageType", propOrder = {
    "packageType",
    "compressionType",
    "value"
})
public class PackageType  implements Serializable {
    private static final long serialVersionUID = 1L;

    @XmlElement(name = "PackageType", required = true)
    @XmlSchemaType(name = "string")
    protected PackageTypeType packageType;
    @XmlElement(name = "CompressionType", required = true)
    @XmlSchemaType(name = "string")
    protected CompressionTypeType compressionType;
    @XmlElement(name = "Value", required = true)
    protected String value;

    /**
     * Gets the value of the packageType property.
     * 
     * @return
     *     possible object is
     *     {@link PackageTypeType }
     *     
     */
    public PackageTypeType getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageTypeType }
     *     
     */
    public void setPackageType(PackageTypeType value) {
        this.packageType = value;
    }

    /**
     * Gets the value of the compressionType property.
     * 
     * @return
     *     possible object is
     *     {@link CompressionTypeType }
     *     
     */
    public CompressionTypeType getCompressionType() {
        return compressionType;
    }

    /**
     * Sets the value of the compressionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompressionTypeType }
     *     
     */
    public void setCompressionType(CompressionTypeType value) {
        this.compressionType = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
