<?php error_reporting(0);
  if(session_status()!=2){     session_start(); };
  require_once($_SERVER['DOCUMENT_ROOT'].'/resources/php/Rb.php');
  R::setup('mysql:host=localhost;dbname=tb152026_testdane', 'tb152026_madrylo','Testdane7005*');
  $id = $_POST['Nidtest'];
  $nazwatestu = $_POST['Nnazwatest'];
  $tresc = $_POST['Nttresc'];
  $rodzaj = $_POST['Ntrodzaj'];
  $pytanie = $_POST['Ntpytanie'];
  $odp1 = $_POST['Ntodp1'];
  $odp2 = $_POST['Ntodp2'];
  $odp3 = $_POST['Ntodp3'];
  $odp4 = $_POST['Ntodp4'];
  $odp1w = isset($_POST['Ntodp1w']) ? 'true' : 'false';
  $odp2w = isset($_POST['Ntodp2w']) ? 'true' : 'false';
  $odp3w = isset($_POST['Ntodp3w']) ? 'true' : 'false';
  $odp4w = isset($_POST['Ntodp4w']) ? 'true' : 'false';
  $sql = "INSERT INTO `test` (`id` ,`nazwatest` ,`tresc` ,`rodzaj`,`pytanie`,`odp1`,`odp2`,`odp3`,`odp4`,`odp1walidacja`,`odp2walidacja`,`odp3walidacja`,`odp4walidacja`) VALUES ('$id', '$nazwatestu', '$tresc', '$rodzaj', '$pytanie', '$odp1', '$odp2', '$odp3', '$odp4', '$odp1w', '$odp2w', '$odp3w', '$odp4w');";
  R::exec($sql);
  echo R::getCell("SELECT `id` FROM  `test` WHERE  (`nazwatest` = '$nazwatestu' AND  `tresc` =  '$tresc' AND `pytanie` = '$pytanie')");
?>
