//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 12:02:07 AM CEST 
//


package pl.gov.crd.wzor._2020._05._08._9393;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDowoduZakupu.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TDowoduZakupu">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MK"/>
 *     &lt;enumeration value="VAT_RR"/>
 *     &lt;enumeration value="WEW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TDowoduZakupu")
@XmlEnum
public enum TDowoduZakupu {


    /**
     * MK - Faktura wystawiona przez podatnika będącego dostawcą lub usługodawcą, który wybrał metodę kasową rozliczeń określoną w art. 21 ustawy
     * 
     */
    MK,

    /**
     * VAT_RR - Faktura VAT RR, o której mowa w art. 116 ustawy
     * 
     */
    VAT_RR,

    /**
     * WEW - Dokument wewnętrzny
     * 
     */
    WEW;

    public String value() {
        return name();
    }

    public static TDowoduZakupu fromValue(String v) {
        return valueOf(v);
    }

}
