//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.20 at 11:22:28 PM CET 
//


package pl.zus._2020.kedu_5_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_program complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_program">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="producent" type="{http://www.zus.pl/2020/KEDU_5_2}t_program_producent"/>
 *         &lt;element name="symbol" type="{http://www.zus.pl/2020/KEDU_5_2}t_program_symbol"/>
 *         &lt;element name="wersja" type="{http://www.zus.pl/2020/KEDU_5_2}t_program_wersja"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_program", propOrder = {
    "producent",
    "symbol",
    "wersja"
})
public class TProgram {

    @XmlElement(required = true)
    protected String producent;
    @XmlElement(required = true)
    protected String symbol;
    @XmlElement(required = true)
    protected String wersja;

    /**
     * Gets the value of the producent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducent() {
        return producent;
    }

    /**
     * Sets the value of the producent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducent(String value) {
        this.producent = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the wersja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWersja() {
        return wersja;
    }

    /**
     * Sets the value of the wersja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWersja(String value) {
        this.wersja = value;
    }

}
