//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.27 at 09:55:56 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://crd.gov.pl/wzor/2021/08/03/08031/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.gov.crd.wzor._2021._08._03._08031;
