//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.18 at 06:04:53 PM CEST 
//


package pl.com.cdn.optima.offline;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.com.cdn.optima.offline package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATKODYJPKKODJPK_QNAME = new QName("http://www.cdn.com.pl/optima/offline", "KOD_JPK");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.com.cdn.optima.offline
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ROOT }
     * 
     */
    public ROOT createROOT() {
        return new ROOT();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT createROOTREJESTRYSPRZEDAZYVAT() {
        return new ROOT.REJESTRYSPRZEDAZYVAT();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVAT() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATKODYJPK() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.PLATNOSCI }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.PLATNOSCI createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATPLATNOSCI() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.PLATNOSCI();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.POZYCJE }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.POZYCJE createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATPOZYCJE() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.POZYCJE();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI }
     * 
     */
    public ROOT.KONTRAHENCI createROOTKONTRAHENCI() {
        return new ROOT.KONTRAHENCI();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT createROOTKONTRAHENCIKONTRAHENT() {
        return new ROOT.KONTRAHENCI.KONTRAHENT();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT.PRZEDSTAWICIELE }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT.PRZEDSTAWICIELE createROOTKONTRAHENCIKONTRAHENTPRZEDSTAWICIELE() {
        return new ROOT.KONTRAHENCI.KONTRAHENT.PRZEDSTAWICIELE();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT.GRUPY }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT.GRUPY createROOTKONTRAHENCIKONTRAHENTGRUPY() {
        return new ROOT.KONTRAHENCI.KONTRAHENT.GRUPY();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT.ADRESY }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT.ADRESY createROOTKONTRAHENCIKONTRAHENTADRESY() {
        return new ROOT.KONTRAHENCI.KONTRAHENT.ADRESY();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATKODYJPKKODJPK() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.PLATNOSCI.PLATNOSC }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.PLATNOSCI.PLATNOSC createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATPLATNOSCIPLATNOSC() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.PLATNOSCI.PLATNOSC();
    }

    /**
     * Create an instance of {@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.POZYCJE.POZYCJA }
     * 
     */
    public ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.POZYCJE.POZYCJA createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATPOZYCJEPOZYCJA() {
        return new ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.POZYCJE.POZYCJA();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT.PRZEDSTAWICIELE.PRZEDSTAWICIEL }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT.PRZEDSTAWICIELE.PRZEDSTAWICIEL createROOTKONTRAHENCIKONTRAHENTPRZEDSTAWICIELEPRZEDSTAWICIEL() {
        return new ROOT.KONTRAHENCI.KONTRAHENT.PRZEDSTAWICIELE.PRZEDSTAWICIEL();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT.GRUPY.GRUPA }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT.GRUPY.GRUPA createROOTKONTRAHENCIKONTRAHENTGRUPYGRUPA() {
        return new ROOT.KONTRAHENCI.KONTRAHENT.GRUPY.GRUPA();
    }

    /**
     * Create an instance of {@link ROOT.KONTRAHENCI.KONTRAHENT.ADRESY.ADRES }
     * 
     */
    public ROOT.KONTRAHENCI.KONTRAHENT.ADRESY.ADRES createROOTKONTRAHENCIKONTRAHENTADRESYADRES() {
        return new ROOT.KONTRAHENCI.KONTRAHENT.ADRESY.ADRES();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cdn.com.pl/optima/offline", name = "KOD_JPK", scope = ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.class)
    public JAXBElement<ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK> createROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATKODYJPKKODJPK(ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK value) {
        return new JAXBElement<ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK>(_ROOTREJESTRYSPRZEDAZYVATREJESTRSPRZEDAZYVATKODYJPKKODJPK_QNAME, ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.KODJPK.class, ROOT.REJESTRYSPRZEDAZYVAT.REJESTRSPRZEDAZYVAT.KODYJPK.class, value);
    }

}
