//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.27 at 09:55:56 AM CEST 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2021._03._12.ed.definicjetypyoss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EUTraderID_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EUTraderID_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="VATIdentificationNumber" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/03/12/eD/DefinicjeTypyOss/}OtherVATNumber_Type"/>
 *         &lt;element name="TaxReferenceNumber" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/03/12/eD/DefinicjeTypyOss/}VATNumberOrTIN_Type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EUTraderID_Type", propOrder = {
    "vatIdentificationNumber",
    "taxReferenceNumber"
})
public class EUTraderIDType {

    @XmlElement(name = "VATIdentificationNumber")
    protected OtherVATNumberType vatIdentificationNumber;
    @XmlElement(name = "TaxReferenceNumber")
    protected VATNumberOrTINType taxReferenceNumber;

    /**
     * Gets the value of the vatIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link OtherVATNumberType }
     *     
     */
    public OtherVATNumberType getVATIdentificationNumber() {
        return vatIdentificationNumber;
    }

    /**
     * Sets the value of the vatIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherVATNumberType }
     *     
     */
    public void setVATIdentificationNumber(OtherVATNumberType value) {
        this.vatIdentificationNumber = value;
    }

    /**
     * Gets the value of the taxReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link VATNumberOrTINType }
     *     
     */
    public VATNumberOrTINType getTaxReferenceNumber() {
        return taxReferenceNumber;
    }

    /**
     * Sets the value of the taxReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link VATNumberOrTINType }
     *     
     */
    public void setTaxReferenceNumber(VATNumberOrTINType value) {
        this.taxReferenceNumber = value;
    }

}
