//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.31 at 07:59:47 PM CET 
//


package deklaracje.vat717;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the deklaracje.vat717 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: deklaracje.vat717
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Deklaracja }
     * 
     */
    public Deklaracja createDeklaracja() {
        return new Deklaracja();
    }

    /**
     * Create an instance of {@link WniosekVATZZ }
     * 
     */
    public WniosekVATZZ createWniosekVATZZ() {
        return new WniosekVATZZ();
    }

    /**
     * Create an instance of {@link WniosekVATZT }
     * 
     */
    public WniosekVATZT createWniosekVATZT() {
        return new WniosekVATZT();
    }

    /**
     * Create an instance of {@link WniosekVATZD }
     * 
     */
    public WniosekVATZD createWniosekVATZD() {
        return new WniosekVATZD();
    }

    /**
     * Create an instance of {@link ZalacznikORDZU }
     * 
     */
    public ZalacznikORDZU createZalacznikORDZU() {
        return new ZalacznikORDZU();
    }

    /**
     * Create an instance of {@link ZalacznikORDZU.PozycjeSzczegolowe }
     * 
     */
    public ZalacznikORDZU.PozycjeSzczegolowe createZalacznikORDZUPozycjeSzczegolowe() {
        return new ZalacznikORDZU.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekORDZU }
     * 
     */
    public TNaglowekORDZU createTNaglowekORDZU() {
        return new TNaglowekORDZU();
    }

    /**
     * Create an instance of {@link WniosekVATZD.PozycjeSzczegolowe }
     * 
     */
    public WniosekVATZD.PozycjeSzczegolowe createWniosekVATZDPozycjeSzczegolowe() {
        return new WniosekVATZD.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekVATZD }
     * 
     */
    public TNaglowekVATZD createTNaglowekVATZD() {
        return new TNaglowekVATZD();
    }

    /**
     * Create an instance of {@link WniosekVATZT.PozycjeSzczegolowe }
     * 
     */
    public WniosekVATZT.PozycjeSzczegolowe createWniosekVATZTPozycjeSzczegolowe() {
        return new WniosekVATZT.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekVATZT }
     * 
     */
    public TNaglowekVATZT createTNaglowekVATZT() {
        return new TNaglowekVATZT();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna }
     * 
     */
    public TOsobaFizycznaPelna createTOsobaFizycznaPelna() {
        return new TOsobaFizycznaPelna();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny }
     * 
     */
    public TPodmiotDowolnyPelny createTPodmiotDowolnyPelny() {
        return new TPodmiotDowolnyPelny();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna }
     * 
     */
    public TOsobaFizyczna createTOsobaFizyczna() {
        return new TOsobaFizyczna();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna }
     * 
     */
    public TOsobaNiefizycznaPelna createTOsobaNiefizycznaPelna() {
        return new TOsobaNiefizycznaPelna();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna2 }
     * 
     */
    public TOsobaFizyczna2 createTOsobaFizyczna2() {
        return new TOsobaFizyczna2();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna }
     * 
     */
    public TOsobaNiefizyczna createTOsobaNiefizyczna() {
        return new TOsobaNiefizyczna();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna1 }
     * 
     */
    public TOsobaFizyczna1 createTOsobaFizyczna1() {
        return new TOsobaFizyczna1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny }
     * 
     */
    public TPodmiotDowolny createTPodmiotDowolny() {
        return new TPodmiotDowolny();
    }

    /**
     * Create an instance of {@link WniosekVATZZ.PozycjeSzczegolowe }
     * 
     */
    public WniosekVATZZ.PozycjeSzczegolowe createWniosekVATZZPozycjeSzczegolowe() {
        return new WniosekVATZZ.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekVATZZ }
     * 
     */
    public TNaglowekVATZZ createTNaglowekVATZZ() {
        return new TNaglowekVATZZ();
    }

    /**
     * Create an instance of {@link TNaglowek }
     * 
     */
    public TNaglowek createTNaglowek() {
        return new TNaglowek();
    }

    /**
     * Create an instance of {@link Deklaracja.Podmiot1 }
     * 
     */
    public Deklaracja.Podmiot1 createDeklaracjaPodmiot1() {
        return new Deklaracja.Podmiot1();
    }

    /**
     * Create an instance of {@link deklaracje.vat717.PozycjeSzczegolowe }
     * 
     */
    public deklaracje.vat717.PozycjeSzczegolowe createPozycjeSzczegolowe() {
        return new deklaracje.vat717.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link Deklaracja.Zalaczniki }
     * 
     */
    public Deklaracja.Zalaczniki createDeklaracjaZalaczniki() {
        return new Deklaracja.Zalaczniki();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej1 }
     * 
     */
    public TIdentyfikatorOsobyFizycznej1 createTIdentyfikatorOsobyFizycznej1() {
        return new TIdentyfikatorOsobyFizycznej1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej2 }
     * 
     */
    public TIdentyfikatorOsobyFizycznej2 createTIdentyfikatorOsobyFizycznej2() {
        return new TIdentyfikatorOsobyFizycznej2();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznejPelny }
     * 
     */
    public TIdentyfikatorOsobyFizycznejPelny createTIdentyfikatorOsobyFizycznejPelny() {
        return new TIdentyfikatorOsobyFizycznejPelny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej }
     * 
     */
    public TIdentyfikatorOsobyFizycznej createTIdentyfikatorOsobyFizycznej() {
        return new TIdentyfikatorOsobyFizycznej();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznejZagranicznej }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznejZagranicznej createTIdentyfikatorOsobyNiefizycznejZagranicznej() {
        return new TIdentyfikatorOsobyNiefizycznejZagranicznej();
    }

    /**
     * Create an instance of {@link TAdres }
     * 
     */
    public TAdres createTAdres() {
        return new TAdres();
    }

    /**
     * Create an instance of {@link TAdresPolski }
     * 
     */
    public TAdresPolski createTAdresPolski() {
        return new TAdresPolski();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu }
     * 
     */
    public TPodmiotDowolnyBezAdresu createTPodmiotDowolnyBezAdresu() {
        return new TPodmiotDowolnyBezAdresu();
    }

    /**
     * Create an instance of {@link TAdresZagraniczny }
     * 
     */
    public TAdresZagraniczny createTAdresZagraniczny() {
        return new TAdresZagraniczny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznej }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznej createTIdentyfikatorOsobyNiefizycznej() {
        return new TIdentyfikatorOsobyNiefizycznej();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu2 }
     * 
     */
    public TPodmiotDowolnyBezAdresu2 createTPodmiotDowolnyBezAdresu2() {
        return new TPodmiotDowolnyBezAdresu2();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu1 }
     * 
     */
    public TPodmiotDowolnyBezAdresu1 createTPodmiotDowolnyBezAdresu1() {
        return new TPodmiotDowolnyBezAdresu1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznejPelny }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznejPelny createTIdentyfikatorOsobyNiefizycznejPelny() {
        return new TIdentyfikatorOsobyNiefizycznejPelny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznejZagranicznej }
     * 
     */
    public TIdentyfikatorOsobyFizycznejZagranicznej createTIdentyfikatorOsobyFizycznejZagranicznej() {
        return new TIdentyfikatorOsobyFizycznejZagranicznej();
    }

    /**
     * Create an instance of {@link ZalacznikORDZU.PozycjeSzczegolowe.P13 }
     * 
     */
    public ZalacznikORDZU.PozycjeSzczegolowe.P13 createZalacznikORDZUPozycjeSzczegoloweP13() {
        return new ZalacznikORDZU.PozycjeSzczegolowe.P13();
    }

    /**
     * Create an instance of {@link TNaglowekORDZU.KodFormularza }
     * 
     */
    public TNaglowekORDZU.KodFormularza createTNaglowekORDZUKodFormularza() {
        return new TNaglowekORDZU.KodFormularza();
    }

    /**
     * Create an instance of {@link WniosekVATZD.PozycjeSzczegolowe.PB }
     * 
     */
    public WniosekVATZD.PozycjeSzczegolowe.PB createWniosekVATZDPozycjeSzczegolowePB() {
        return new WniosekVATZD.PozycjeSzczegolowe.PB();
    }

    /**
     * Create an instance of {@link TNaglowekVATZD.KodFormularza }
     * 
     */
    public TNaglowekVATZD.KodFormularza createTNaglowekVATZDKodFormularza() {
        return new TNaglowekVATZD.KodFormularza();
    }

    /**
     * Create an instance of {@link WniosekVATZT.PozycjeSzczegolowe.P11 }
     * 
     */
    public WniosekVATZT.PozycjeSzczegolowe.P11 createWniosekVATZTPozycjeSzczegoloweP11() {
        return new WniosekVATZT.PozycjeSzczegolowe.P11();
    }

    /**
     * Create an instance of {@link TNaglowekVATZT.KodFormularza }
     * 
     */
    public TNaglowekVATZT.KodFormularza createTNaglowekVATZTKodFormularza() {
        return new TNaglowekVATZT.KodFormularza();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna.AdresZamieszkania }
     * 
     */
    public TOsobaFizycznaPelna.AdresZamieszkania createTOsobaFizycznaPelnaAdresZamieszkania() {
        return new TOsobaFizycznaPelna.AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby createTPodmiotDowolnyPelnyAdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna.AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna.AdresZamieszkania createTOsobaFizycznaAdresZamieszkania() {
        return new TOsobaFizyczna.AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna.AdresSiedziby }
     * 
     */
    public TOsobaNiefizycznaPelna.AdresSiedziby createTOsobaNiefizycznaPelnaAdresSiedziby() {
        return new TOsobaNiefizycznaPelna.AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna2 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna2 .AdresZamieszkania createTOsobaFizyczna2AdresZamieszkania() {
        return new TOsobaFizyczna2 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna.AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna.AdresSiedziby createTOsobaNiefizycznaAdresSiedziby() {
        return new TOsobaNiefizyczna.AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna1 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna1 .AdresZamieszkania createTOsobaFizyczna1AdresZamieszkania() {
        return new TOsobaFizyczna1 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny.AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny.AdresZamieszkaniaSiedziby createTPodmiotDowolnyAdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny.AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link WniosekVATZZ.PozycjeSzczegolowe.P10 }
     * 
     */
    public WniosekVATZZ.PozycjeSzczegolowe.P10 createWniosekVATZZPozycjeSzczegoloweP10() {
        return new WniosekVATZZ.PozycjeSzczegolowe.P10();
    }

    /**
     * Create an instance of {@link TNaglowekVATZZ.KodFormularza }
     * 
     */
    public TNaglowekVATZZ.KodFormularza createTNaglowekVATZZKodFormularza() {
        return new TNaglowekVATZZ.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowek.KodFormularza }
     * 
     */
    public TNaglowek.KodFormularza createTNaglowekKodFormularza() {
        return new TNaglowek.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowek.CelZlozenia }
     * 
     */
    public TNaglowek.CelZlozenia createTNaglowekCelZlozenia() {
        return new TNaglowek.CelZlozenia();
    }

}
