//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.30 at 12:51:44 PM CET 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._03._15.ed.ordzu;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._03._15.ed.ordzu package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._03._15.ed.ordzu
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalacznikORDZU }
     * 
     */
    public ZalacznikORDZU createZalacznikORDZU() {
        return new ZalacznikORDZU();
    }

    /**
     * Create an instance of {@link TNaglowekORDZU }
     * 
     */
    public TNaglowekORDZU createTNaglowekORDZU() {
        return new TNaglowekORDZU();
    }

    /**
     * Create an instance of {@link ZalacznikORDZU.PozycjeSzczegolowe }
     * 
     */
    public ZalacznikORDZU.PozycjeSzczegolowe createZalacznikORDZUPozycjeSzczegolowe() {
        return new ZalacznikORDZU.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekORDZU.KodFormularza }
     * 
     */
    public TNaglowekORDZU.KodFormularza createTNaglowekORDZUKodFormularza() {
        return new TNaglowekORDZU.KodFormularza();
    }

}
