//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 08:31:20 PM CEST 
//


package deklaracje.vat272;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_C1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TCalkowity">
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="P_C2" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TZnakowy"/>
 *         &lt;element name="P_C3" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
 *         &lt;element name="P_C4" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwota2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pc1",
    "pc2",
    "pc3",
    "pc4"
})
@XmlRootElement(name = "Grupa_C", namespace = "http://crd.gov.pl/wzor/2017/01/11/3844/")
public class GrupaC {

    @XmlElement(name = "P_C1", namespace = "http://crd.gov.pl/wzor/2017/01/11/3844/")
    protected Integer pc1;
    @XmlElement(name = "P_C2", namespace = "http://crd.gov.pl/wzor/2017/01/11/3844/", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String pc2;
    @XmlElement(name = "P_C3", namespace = "http://crd.gov.pl/wzor/2017/01/11/3844/", required = true)
    protected String pc3;
    @XmlElement(name = "P_C4", namespace = "http://crd.gov.pl/wzor/2017/01/11/3844/", required = true)
    protected BigDecimal pc4;
    @XmlAttribute(name = "typ", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String typ;

    /**
     * Gets the value of the pc1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPC1() {
        return pc1;
    }

    /**
     * Sets the value of the pc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPC1(Integer value) {
        this.pc1 = value;
    }

    /**
     * Gets the value of the pc2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC2() {
        return pc2;
    }

    /**
     * Sets the value of the pc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC2(String value) {
        this.pc2 = value;
    }

    /**
     * Gets the value of the pc3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3() {
        return pc3;
    }

    /**
     * Sets the value of the pc3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3(String value) {
        this.pc3 = value;
    }

    /**
     * Gets the value of the pc4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPC4() {
        return pc4;
    }

    /**
     * Sets the value of the pc4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPC4(BigDecimal value) {
        this.pc4 = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyp() {
        if (typ == null) {
            return "G";
        } else {
            return typ;
        }
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyp(String value) {
        this.typ = value;
    }

}
