//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.11 at 05:25:37 AM CEST 
//


package deklaracje.vat18m;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_11" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_13" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;element name="P_22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_24" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;element name="P_31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_34" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_35" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;element name="P_36" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_37" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_38" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_39" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element name="P_40" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *           &lt;element name="P_41" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;element name="P_42" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_43" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_44" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_45" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *           &lt;element name="P_46" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC"/>
 *         &lt;/sequence>
 *         &lt;element name="P_47" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;element name="P_48" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;element name="P_49" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC">
 *               &lt;maxInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="P_50" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_51" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC" minOccurs="0"/>
 *         &lt;element name="P_52" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_53" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_54" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_55" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_56" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_57" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *           &lt;choice minOccurs="0">
 *             &lt;sequence>
 *               &lt;element name="P_58" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *               &lt;element name="P_68" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1"/>
 *             &lt;/sequence>
 *             &lt;sequence>
 *               &lt;element name="P_59" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *               &lt;element name="P_70" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1_2"/>
 *             &lt;/sequence>
 *             &lt;element name="P_60" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *             &lt;element name="P_61" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *           &lt;/choice>
 *           &lt;element name="P_69" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1_2"/>
 *         &lt;/sequence>
 *         &lt;element name="P_62" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *         &lt;element name="P_63" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *         &lt;element name="P_64" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *         &lt;element name="P_65" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *         &lt;element name="P_66" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *         &lt;element name="P_67" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *         &lt;element name="P_71" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1_2" minOccurs="0"/>
 *         &lt;element name="P_74" type="{http://crd.gov.pl/wzor/2018/05/17/5376/}TAdresEmail" minOccurs="0"/>
 *         &lt;element name="P_75" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TZnakowy">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="P_76" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TData">
 *               &lt;minInclusive value="2018-07-01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "p10",
    "p11",
    "p12",
    "p13",
    "p14",
    "p15",
    "p16",
    "p17",
    "p18",
    "p19",
    "p20",
    "p21",
    "p22",
    "p23",
    "p24",
    "p25",
    "p26",
    "p27",
    "p28",
    "p29",
    "p30",
    "p31",
    "p32",
    "p33",
    "p34",
    "p35",
    "p36",
    "p37",
    "p38",
    "p39",
    "p40",
    "p41",
    "p42",
    "p43",
    "p44",
    "p45",
    "p46",
    "p47",
    "p48",
    "p49",
    "p50",
    "p51",
    "p52",
    "p53",
    "p54",
    "p55",
    "p56",
    "p57",
    "p58",
    "p68",
    "p59",
    "p70",
    "p60",
    "p61",
    "p69",
    "p62",
    "p63",
    "p64",
    "p65",
    "p66",
    "p67",
    "p71",
    "p74",
    "p75",
    "p76"
})
@XmlRootElement(name = "PozycjeSzczegolowe", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
public class PozycjeSzczegolowe {

    @XmlElement(name = "P_10", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p10;
    @XmlElement(name = "P_11", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p11;
    @XmlElement(name = "P_12", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p12;
    @XmlElement(name = "P_13", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p13;
    @XmlElement(name = "P_14", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p14;
    @XmlElement(name = "P_15", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p15;
    @XmlElement(name = "P_16", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p16;
    @XmlElement(name = "P_17", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p17;
    @XmlElement(name = "P_18", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p18;
    @XmlElement(name = "P_19", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p19;
    @XmlElement(name = "P_20", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p20;
    @XmlElement(name = "P_21", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p21;
    @XmlElement(name = "P_22", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p22;
    @XmlElement(name = "P_23", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p23;
    @XmlElement(name = "P_24", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p24;
    @XmlElement(name = "P_25", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p25;
    @XmlElement(name = "P_26", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p26;
    @XmlElement(name = "P_27", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p27;
    @XmlElement(name = "P_28", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p28;
    @XmlElement(name = "P_29", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p29;
    @XmlElement(name = "P_30", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p30;
    @XmlElement(name = "P_31", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p31;
    @XmlElement(name = "P_32", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p32;
    @XmlElement(name = "P_33", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p33;
    @XmlElement(name = "P_34", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p34;
    @XmlElement(name = "P_35", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p35;
    @XmlElement(name = "P_36", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p36;
    @XmlElement(name = "P_37", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p37;
    @XmlElement(name = "P_38", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p38;
    @XmlElement(name = "P_39", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p39;
    @XmlElement(name = "P_40", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p40;
    @XmlElement(name = "P_41", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/", required = true)
    protected BigInteger p41;
    @XmlElement(name = "P_42", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p42;
    @XmlElement(name = "P_43", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p43;
    @XmlElement(name = "P_44", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p44;
    @XmlElement(name = "P_45", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p45;
    @XmlElement(name = "P_46", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p46;
    @XmlElement(name = "P_47", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p47;
    @XmlElement(name = "P_48", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p48;
    @XmlElement(name = "P_49", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p49;
    @XmlElement(name = "P_50", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p50;
    @XmlElement(name = "P_51", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p51;
    @XmlElement(name = "P_52", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p52;
    @XmlElement(name = "P_53", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p53;
    @XmlElement(name = "P_54", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p54;
    @XmlElement(name = "P_55", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p55;
    @XmlElement(name = "P_56", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p56;
    @XmlElement(name = "P_57", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p57;
    @XmlElement(name = "P_58", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p58;
    @XmlElement(name = "P_68", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p68;
    @XmlElement(name = "P_59", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p59;
    @XmlElement(name = "P_70", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p70;
    @XmlElement(name = "P_60", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p60;
    @XmlElement(name = "P_61", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p61;
    @XmlElement(name = "P_69", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p69;
    @XmlElement(name = "P_62", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected BigInteger p62;
    @XmlElement(name = "P_63", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p63;
    @XmlElement(name = "P_64", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p64;
    @XmlElement(name = "P_65", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p65;
    @XmlElement(name = "P_66", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p66;
    @XmlElement(name = "P_67", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p67;
    @XmlElement(name = "P_71", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected Byte p71;
    @XmlElement(name = "P_74", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String p74;
    @XmlElement(name = "P_75", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String p75;
    @XmlElement(name = "P_76", namespace = "http://crd.gov.pl/wzor/2018/05/17/5376/")
    protected XMLGregorianCalendar p76;

    /**
     * Gets the value of the p10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP10() {
        return p10;
    }

    /**
     * Sets the value of the p10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP10(BigInteger value) {
        this.p10 = value;
    }

    /**
     * Gets the value of the p11 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP11() {
        return p11;
    }

    /**
     * Sets the value of the p11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP11(BigInteger value) {
        this.p11 = value;
    }

    /**
     * Gets the value of the p12 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP12() {
        return p12;
    }

    /**
     * Sets the value of the p12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP12(BigInteger value) {
        this.p12 = value;
    }

    /**
     * Gets the value of the p13 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP13() {
        return p13;
    }

    /**
     * Sets the value of the p13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP13(BigInteger value) {
        this.p13 = value;
    }

    /**
     * Gets the value of the p14 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP14() {
        return p14;
    }

    /**
     * Sets the value of the p14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP14(BigInteger value) {
        this.p14 = value;
    }

    /**
     * Gets the value of the p15 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP15() {
        return p15;
    }

    /**
     * Sets the value of the p15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP15(BigInteger value) {
        this.p15 = value;
    }

    /**
     * Gets the value of the p16 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP16() {
        return p16;
    }

    /**
     * Sets the value of the p16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP16(BigInteger value) {
        this.p16 = value;
    }

    /**
     * Gets the value of the p17 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP17() {
        return p17;
    }

    /**
     * Sets the value of the p17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP17(BigInteger value) {
        this.p17 = value;
    }

    /**
     * Gets the value of the p18 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP18() {
        return p18;
    }

    /**
     * Sets the value of the p18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP18(BigInteger value) {
        this.p18 = value;
    }

    /**
     * Gets the value of the p19 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP19() {
        return p19;
    }

    /**
     * Sets the value of the p19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP19(BigInteger value) {
        this.p19 = value;
    }

    /**
     * Gets the value of the p20 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP20() {
        return p20;
    }

    /**
     * Sets the value of the p20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP20(BigInteger value) {
        this.p20 = value;
    }

    /**
     * Gets the value of the p21 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP21() {
        return p21;
    }

    /**
     * Sets the value of the p21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP21(BigInteger value) {
        this.p21 = value;
    }

    /**
     * Gets the value of the p22 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP22() {
        return p22;
    }

    /**
     * Sets the value of the p22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP22(BigInteger value) {
        this.p22 = value;
    }

    /**
     * Gets the value of the p23 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP23() {
        return p23;
    }

    /**
     * Sets the value of the p23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP23(BigInteger value) {
        this.p23 = value;
    }

    /**
     * Gets the value of the p24 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP24() {
        return p24;
    }

    /**
     * Sets the value of the p24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP24(BigInteger value) {
        this.p24 = value;
    }

    /**
     * Gets the value of the p25 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP25() {
        return p25;
    }

    /**
     * Sets the value of the p25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP25(BigInteger value) {
        this.p25 = value;
    }

    /**
     * Gets the value of the p26 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP26() {
        return p26;
    }

    /**
     * Sets the value of the p26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP26(BigInteger value) {
        this.p26 = value;
    }

    /**
     * Gets the value of the p27 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP27() {
        return p27;
    }

    /**
     * Sets the value of the p27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP27(BigInteger value) {
        this.p27 = value;
    }

    /**
     * Gets the value of the p28 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP28() {
        return p28;
    }

    /**
     * Sets the value of the p28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP28(BigInteger value) {
        this.p28 = value;
    }

    /**
     * Gets the value of the p29 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP29() {
        return p29;
    }

    /**
     * Sets the value of the p29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP29(BigInteger value) {
        this.p29 = value;
    }

    /**
     * Gets the value of the p30 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP30() {
        return p30;
    }

    /**
     * Sets the value of the p30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP30(BigInteger value) {
        this.p30 = value;
    }

    /**
     * Gets the value of the p31 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP31() {
        return p31;
    }

    /**
     * Sets the value of the p31 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP31(BigInteger value) {
        this.p31 = value;
    }

    /**
     * Gets the value of the p32 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP32() {
        return p32;
    }

    /**
     * Sets the value of the p32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP32(BigInteger value) {
        this.p32 = value;
    }

    /**
     * Gets the value of the p33 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP33() {
        return p33;
    }

    /**
     * Sets the value of the p33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP33(BigInteger value) {
        this.p33 = value;
    }

    /**
     * Gets the value of the p34 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP34() {
        return p34;
    }

    /**
     * Sets the value of the p34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP34(BigInteger value) {
        this.p34 = value;
    }

    /**
     * Gets the value of the p35 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP35() {
        return p35;
    }

    /**
     * Sets the value of the p35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP35(BigInteger value) {
        this.p35 = value;
    }

    /**
     * Gets the value of the p36 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP36() {
        return p36;
    }

    /**
     * Sets the value of the p36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP36(BigInteger value) {
        this.p36 = value;
    }

    /**
     * Gets the value of the p37 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP37() {
        return p37;
    }

    /**
     * Sets the value of the p37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP37(BigInteger value) {
        this.p37 = value;
    }

    /**
     * Gets the value of the p38 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP38() {
        return p38;
    }

    /**
     * Sets the value of the p38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP38(BigInteger value) {
        this.p38 = value;
    }

    /**
     * Gets the value of the p39 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP39() {
        return p39;
    }

    /**
     * Sets the value of the p39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP39(BigInteger value) {
        this.p39 = value;
    }

    /**
     * Gets the value of the p40 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP40() {
        return p40;
    }

    /**
     * Sets the value of the p40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP40(BigInteger value) {
        this.p40 = value;
    }

    /**
     * Gets the value of the p41 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP41() {
        return p41;
    }

    /**
     * Sets the value of the p41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP41(BigInteger value) {
        this.p41 = value;
    }

    /**
     * Gets the value of the p42 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP42() {
        return p42;
    }

    /**
     * Sets the value of the p42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP42(BigInteger value) {
        this.p42 = value;
    }

    /**
     * Gets the value of the p43 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP43() {
        return p43;
    }

    /**
     * Sets the value of the p43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP43(BigInteger value) {
        this.p43 = value;
    }

    /**
     * Gets the value of the p44 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP44() {
        return p44;
    }

    /**
     * Sets the value of the p44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP44(BigInteger value) {
        this.p44 = value;
    }

    /**
     * Gets the value of the p45 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP45() {
        return p45;
    }

    /**
     * Sets the value of the p45 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP45(BigInteger value) {
        this.p45 = value;
    }

    /**
     * Gets the value of the p46 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP46() {
        return p46;
    }

    /**
     * Sets the value of the p46 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP46(BigInteger value) {
        this.p46 = value;
    }

    /**
     * Gets the value of the p47 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP47() {
        return p47;
    }

    /**
     * Sets the value of the p47 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP47(BigInteger value) {
        this.p47 = value;
    }

    /**
     * Gets the value of the p48 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP48() {
        return p48;
    }

    /**
     * Sets the value of the p48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP48(BigInteger value) {
        this.p48 = value;
    }

    /**
     * Gets the value of the p49 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP49() {
        return p49;
    }

    /**
     * Sets the value of the p49 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP49(BigInteger value) {
        this.p49 = value;
    }

    /**
     * Gets the value of the p50 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP50() {
        return p50;
    }

    /**
     * Sets the value of the p50 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP50(BigInteger value) {
        this.p50 = value;
    }

    /**
     * Gets the value of the p51 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP51() {
        return p51;
    }

    /**
     * Sets the value of the p51 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP51(BigInteger value) {
        this.p51 = value;
    }

    /**
     * Gets the value of the p52 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP52() {
        return p52;
    }

    /**
     * Sets the value of the p52 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP52(BigInteger value) {
        this.p52 = value;
    }

    /**
     * Gets the value of the p53 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP53() {
        return p53;
    }

    /**
     * Sets the value of the p53 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP53(BigInteger value) {
        this.p53 = value;
    }

    /**
     * Gets the value of the p54 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP54() {
        return p54;
    }

    /**
     * Sets the value of the p54 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP54(BigInteger value) {
        this.p54 = value;
    }

    /**
     * Gets the value of the p55 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP55() {
        return p55;
    }

    /**
     * Sets the value of the p55 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP55(BigInteger value) {
        this.p55 = value;
    }

    /**
     * Gets the value of the p56 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP56() {
        return p56;
    }

    /**
     * Sets the value of the p56 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP56(BigInteger value) {
        this.p56 = value;
    }

    /**
     * Gets the value of the p57 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP57() {
        return p57;
    }

    /**
     * Sets the value of the p57 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP57(BigInteger value) {
        this.p57 = value;
    }

    /**
     * Gets the value of the p58 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP58() {
        return p58;
    }

    /**
     * Sets the value of the p58 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP58(BigInteger value) {
        this.p58 = value;
    }

    /**
     * Gets the value of the p68 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP68() {
        return p68;
    }

    /**
     * Sets the value of the p68 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP68(Byte value) {
        this.p68 = value;
    }

    /**
     * Gets the value of the p59 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP59() {
        return p59;
    }

    /**
     * Sets the value of the p59 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP59(BigInteger value) {
        this.p59 = value;
    }

    /**
     * Gets the value of the p70 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP70() {
        return p70;
    }

    /**
     * Sets the value of the p70 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP70(Byte value) {
        this.p70 = value;
    }

    /**
     * Gets the value of the p60 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP60() {
        return p60;
    }

    /**
     * Sets the value of the p60 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP60(BigInteger value) {
        this.p60 = value;
    }

    /**
     * Gets the value of the p61 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP61() {
        return p61;
    }

    /**
     * Sets the value of the p61 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP61(BigInteger value) {
        this.p61 = value;
    }

    /**
     * Gets the value of the p69 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP69() {
        return p69;
    }

    /**
     * Sets the value of the p69 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP69(Byte value) {
        this.p69 = value;
    }

    /**
     * Gets the value of the p62 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getP62() {
        return p62;
    }

    /**
     * Sets the value of the p62 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setP62(BigInteger value) {
        this.p62 = value;
    }

    /**
     * Gets the value of the p63 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP63() {
        return p63;
    }

    /**
     * Sets the value of the p63 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP63(Byte value) {
        this.p63 = value;
    }

    /**
     * Gets the value of the p64 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP64() {
        return p64;
    }

    /**
     * Sets the value of the p64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP64(Byte value) {
        this.p64 = value;
    }

    /**
     * Gets the value of the p65 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP65() {
        return p65;
    }

    /**
     * Sets the value of the p65 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP65(Byte value) {
        this.p65 = value;
    }

    /**
     * Gets the value of the p66 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP66() {
        return p66;
    }

    /**
     * Sets the value of the p66 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP66(Byte value) {
        this.p66 = value;
    }

    /**
     * Gets the value of the p67 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP67() {
        return p67;
    }

    /**
     * Sets the value of the p67 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP67(Byte value) {
        this.p67 = value;
    }

    /**
     * Gets the value of the p71 property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getP71() {
        return p71;
    }

    /**
     * Sets the value of the p71 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setP71(Byte value) {
        this.p71 = value;
    }

    /**
     * Gets the value of the p74 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP74() {
        return p74;
    }

    /**
     * Sets the value of the p74 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP74(String value) {
        this.p74 = value;
    }

    /**
     * Gets the value of the p75 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP75() {
        return p75;
    }

    /**
     * Sets the value of the p75 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP75(String value) {
        this.p75 = value;
    }

    /**
     * Gets the value of the p76 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getP76() {
        return p76;
    }

    /**
     * Sets the value of the p76 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setP76(XMLGregorianCalendar value) {
        this.p76 = value;
    }

}
