//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.19 at 02:15:30 PM CEST 
//


package pl.gov.mf.ksef.schema.gtw.svc.online.types._2021._10._01._0001;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import pl.gov.mf.ksef.schema.gtw.svc.types._2021._10._01._0001.SubjectIdentifierByType;
import pl.gov.mf.ksef.schema.gtw.svc.types._2021._10._01._0001.SubjectIdentifierToType;


/**
 * <p>Java class for InvoicePaymentConfirmationTokenDirectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoicePaymentConfirmationTokenDirectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ksef.mf.gov.pl/schema/gtw/svc/online/types/2021/10/01/0001}InvoicePaymentConfirmationTokenType">
 *       &lt;sequence>
 *         &lt;element name="PaymentType" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}NonEmptyString64Type"/>
 *         &lt;element name="SourceIdentifier" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}SubjectIdentifierToType"/>
 *         &lt;element name="DestinationIdentifier" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}SubjectIdentifierByType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoicePaymentConfirmationTokenDirectType", propOrder = {
    "paymentType",
    "sourceIdentifier",
    "destinationIdentifier"
})
public class InvoicePaymentConfirmationTokenDirectType
    extends InvoicePaymentConfirmationTokenType
 implements Serializable {
    private static final long serialVersionUID = 1L;

    @XmlElement(name = "PaymentType", required = true)
    protected String paymentType;
    @XmlElement(name = "SourceIdentifier", required = true)
    protected SubjectIdentifierToType sourceIdentifier;
    @XmlElement(name = "DestinationIdentifier", required = true)
    protected SubjectIdentifierByType destinationIdentifier;

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the sourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectIdentifierToType }
     *     
     */
    public SubjectIdentifierToType getSourceIdentifier() {
        return sourceIdentifier;
    }

    /**
     * Sets the value of the sourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectIdentifierToType }
     *     
     */
    public void setSourceIdentifier(SubjectIdentifierToType value) {
        this.sourceIdentifier = value;
    }

    /**
     * Gets the value of the destinationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectIdentifierByType }
     *     
     */
    public SubjectIdentifierByType getDestinationIdentifier() {
        return destinationIdentifier;
    }

    /**
     * Sets the value of the destinationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectIdentifierByType }
     *     
     */
    public void setDestinationIdentifier(SubjectIdentifierByType value) {
        this.destinationIdentifier = value;
    }

}
