//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.05 at 02:35:54 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zus.pl/2021/KEDU_5_4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.zus._2021.kedu_5_4;
