//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.05 at 02:35:54 AM CEST 
//


package pl.zus._2021.kedu_5_4;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_DDORCA_B complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_DDORCA_B">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="p1" type="{http://www.zus.pl/2021/KEDU_5_4}t_KodTytuluUbezpieczenia_6"/>
 *         &lt;element name="p2" type="{http://www.zus.pl/2021/KEDU_5_4}t_Info_o_Przekr_1" minOccurs="0"/>
 *         &lt;element name="p3" type="{http://www.zus.pl/2021/KEDU_5_4}t_WymiarCzasuPracy_6" minOccurs="0"/>
 *         &lt;element name="p4" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_8" minOccurs="0"/>
 *         &lt;element name="p5" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_8" minOccurs="0"/>
 *         &lt;element name="p6" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_8" minOccurs="0"/>
 *         &lt;element name="p7" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p8" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p9" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p10" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p11" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p12" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p13" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p14" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p15" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p16" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p17" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p18" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p19" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p20" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p21" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p22" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p23" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p24" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p25" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p26" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p27" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p28" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_7" minOccurs="0"/>
 *         &lt;element name="p29" type="{http://www.zus.pl/2021/KEDU_5_4}t_Kwota_8" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_DDORCA_B", propOrder = {
    "p1",
    "p2",
    "p3",
    "p4",
    "p5",
    "p6",
    "p7",
    "p8",
    "p9",
    "p10",
    "p11",
    "p12",
    "p13",
    "p14",
    "p15",
    "p16",
    "p17",
    "p18",
    "p19",
    "p20",
    "p21",
    "p22",
    "p23",
    "p24",
    "p25",
    "p26",
    "p27",
    "p28",
    "p29"
})
public class TDDORCAB {

    @XmlElement(required = true)
    protected TKodTytuluUbezpieczenia6 p1;
    protected String p2;
    protected TWymiarCzasuPracy6 p3;
    protected BigDecimal p4;
    protected BigDecimal p5;
    protected BigDecimal p6;
    protected BigDecimal p7;
    protected BigDecimal p8;
    protected BigDecimal p9;
    protected BigDecimal p10;
    protected BigDecimal p11;
    protected BigDecimal p12;
    protected BigDecimal p13;
    protected BigDecimal p14;
    protected BigDecimal p15;
    protected BigDecimal p16;
    protected BigDecimal p17;
    protected BigDecimal p18;
    protected BigDecimal p19;
    protected BigDecimal p20;
    protected BigDecimal p21;
    protected BigDecimal p22;
    protected BigDecimal p23;
    protected BigDecimal p24;
    protected BigDecimal p25;
    protected BigDecimal p26;
    protected BigDecimal p27;
    protected BigDecimal p28;
    protected BigDecimal p29;

    /**
     * Gets the value of the p1 property.
     * 
     * @return
     *     possible object is
     *     {@link TKodTytuluUbezpieczenia6 }
     *     
     */
    public TKodTytuluUbezpieczenia6 getP1() {
        return p1;
    }

    /**
     * Sets the value of the p1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodTytuluUbezpieczenia6 }
     *     
     */
    public void setP1(TKodTytuluUbezpieczenia6 value) {
        this.p1 = value;
    }

    /**
     * Gets the value of the p2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP2() {
        return p2;
    }

    /**
     * Sets the value of the p2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP2(String value) {
        this.p2 = value;
    }

    /**
     * Gets the value of the p3 property.
     * 
     * @return
     *     possible object is
     *     {@link TWymiarCzasuPracy6 }
     *     
     */
    public TWymiarCzasuPracy6 getP3() {
        return p3;
    }

    /**
     * Sets the value of the p3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWymiarCzasuPracy6 }
     *     
     */
    public void setP3(TWymiarCzasuPracy6 value) {
        this.p3 = value;
    }

    /**
     * Gets the value of the p4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP4() {
        return p4;
    }

    /**
     * Sets the value of the p4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP4(BigDecimal value) {
        this.p4 = value;
    }

    /**
     * Gets the value of the p5 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP5() {
        return p5;
    }

    /**
     * Sets the value of the p5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP5(BigDecimal value) {
        this.p5 = value;
    }

    /**
     * Gets the value of the p6 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP6() {
        return p6;
    }

    /**
     * Sets the value of the p6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP6(BigDecimal value) {
        this.p6 = value;
    }

    /**
     * Gets the value of the p7 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP7() {
        return p7;
    }

    /**
     * Sets the value of the p7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP7(BigDecimal value) {
        this.p7 = value;
    }

    /**
     * Gets the value of the p8 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP8() {
        return p8;
    }

    /**
     * Sets the value of the p8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP8(BigDecimal value) {
        this.p8 = value;
    }

    /**
     * Gets the value of the p9 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP9() {
        return p9;
    }

    /**
     * Sets the value of the p9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP9(BigDecimal value) {
        this.p9 = value;
    }

    /**
     * Gets the value of the p10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP10() {
        return p10;
    }

    /**
     * Sets the value of the p10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP10(BigDecimal value) {
        this.p10 = value;
    }

    /**
     * Gets the value of the p11 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP11() {
        return p11;
    }

    /**
     * Sets the value of the p11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP11(BigDecimal value) {
        this.p11 = value;
    }

    /**
     * Gets the value of the p12 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP12() {
        return p12;
    }

    /**
     * Sets the value of the p12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP12(BigDecimal value) {
        this.p12 = value;
    }

    /**
     * Gets the value of the p13 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP13() {
        return p13;
    }

    /**
     * Sets the value of the p13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP13(BigDecimal value) {
        this.p13 = value;
    }

    /**
     * Gets the value of the p14 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP14() {
        return p14;
    }

    /**
     * Sets the value of the p14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP14(BigDecimal value) {
        this.p14 = value;
    }

    /**
     * Gets the value of the p15 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP15() {
        return p15;
    }

    /**
     * Sets the value of the p15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP15(BigDecimal value) {
        this.p15 = value;
    }

    /**
     * Gets the value of the p16 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP16() {
        return p16;
    }

    /**
     * Sets the value of the p16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP16(BigDecimal value) {
        this.p16 = value;
    }

    /**
     * Gets the value of the p17 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP17() {
        return p17;
    }

    /**
     * Sets the value of the p17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP17(BigDecimal value) {
        this.p17 = value;
    }

    /**
     * Gets the value of the p18 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP18() {
        return p18;
    }

    /**
     * Sets the value of the p18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP18(BigDecimal value) {
        this.p18 = value;
    }

    /**
     * Gets the value of the p19 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP19() {
        return p19;
    }

    /**
     * Sets the value of the p19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP19(BigDecimal value) {
        this.p19 = value;
    }

    /**
     * Gets the value of the p20 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP20() {
        return p20;
    }

    /**
     * Sets the value of the p20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP20(BigDecimal value) {
        this.p20 = value;
    }

    /**
     * Gets the value of the p21 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP21() {
        return p21;
    }

    /**
     * Sets the value of the p21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP21(BigDecimal value) {
        this.p21 = value;
    }

    /**
     * Gets the value of the p22 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP22() {
        return p22;
    }

    /**
     * Sets the value of the p22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP22(BigDecimal value) {
        this.p22 = value;
    }

    /**
     * Gets the value of the p23 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP23() {
        return p23;
    }

    /**
     * Sets the value of the p23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP23(BigDecimal value) {
        this.p23 = value;
    }

    /**
     * Gets the value of the p24 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP24() {
        return p24;
    }

    /**
     * Sets the value of the p24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP24(BigDecimal value) {
        this.p24 = value;
    }

    /**
     * Gets the value of the p25 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP25() {
        return p25;
    }

    /**
     * Sets the value of the p25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP25(BigDecimal value) {
        this.p25 = value;
    }

    /**
     * Gets the value of the p26 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP26() {
        return p26;
    }

    /**
     * Sets the value of the p26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP26(BigDecimal value) {
        this.p26 = value;
    }

    /**
     * Gets the value of the p27 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP27() {
        return p27;
    }

    /**
     * Sets the value of the p27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP27(BigDecimal value) {
        this.p27 = value;
    }

    /**
     * Gets the value of the p28 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP28() {
        return p28;
    }

    /**
     * Sets the value of the p28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP28(BigDecimal value) {
        this.p28 = value;
    }

    /**
     * Gets the value of the p29 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP29() {
        return p29;
    }

    /**
     * Sets the value of the p29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP29(BigDecimal value) {
        this.p29 = value;
    }

}
