//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.19 at 02:15:30 PM CEST 
//


package pl.gov.mf.ksef.schema.gtw.svc.online.auth.request._2021._10._01._0001;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pl.gov.mf.ksef.schema.gtw.svc.online.types._2021._10._01._0001.AuthorisationContextSignedType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Context" type="{http://ksef.mf.gov.pl/schema/gtw/svc/online/types/2021/10/01/0001}AuthorisationContextSignedType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "context"
})
@XmlRootElement(name = "InitSessionSignedRequest")
public class InitSessionSignedRequest implements Serializable {
    private static final long serialVersionUID = 1L;

    @XmlElement(name = "Context", required = true)
    protected AuthorisationContextSignedType context;

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorisationContextSignedType }
     *     
     */
    public AuthorisationContextSignedType getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorisationContextSignedType }
     *     
     */
    public void setContext(AuthorisationContextSignedType value) {
        this.context = value;
    }

}
