//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 09:13:00 PM CET 
//


package sprawozdania.v12;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naglowek" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOpStruktury}TNaglowekSprawozdaniaFinansowegoOpWZlotych"/>
 *         &lt;choice>
 *           &lt;element name="WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="P_1">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_1A" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaSiedziba"/>
 *                               &lt;element name="P_1B" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TAdresZOpcZagranicznym"/>
 *                               &lt;element name="P_1C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
 *                               &lt;element name="P_1D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrKRS" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_2" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatOpcjonalnych" minOccurs="0"/>
 *                     &lt;element name="P_3" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatSF"/>
 *                     &lt;element name="P_4">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_4A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="P_4B" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="P_4C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_5">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_5A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
 *                               &lt;element name="P_5B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
 *                               &lt;element name="P_5C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
 *                               &lt;element name="P_5D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_6" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TPozycjaUzytkownika" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="P_1">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_1A" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaSiedziba"/>
 *                               &lt;element name="P_1B" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TAdresZOpcZagranicznym"/>
 *                               &lt;element name="P_1C" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}PKDPodstawowaDzialalnosc"/>
 *                               &lt;element name="P_1D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
 *                               &lt;element name="P_1E" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrKRS" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_2" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatOpcjonalnych" minOccurs="0"/>
 *                     &lt;element name="P_3" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatSF"/>
 *                     &lt;element name="P_4" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="P_5">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_5A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="P_5B" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="P_5C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_6" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_6A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="P_6B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_7">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="P_7A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
 *                               &lt;element name="P_7B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
 *                               &lt;element name="P_7C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
 *                               &lt;element name="P_7D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="P_8" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TPozycjaUzytkownika" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="BilansJednostkaOp" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOpStruktury}BilansJednostkaOp"/>
 *           &lt;element name="BilansJednostkaInna" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaStruktury}BilansJednostkaInna"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="RZiSJednostkaOp" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOpStruktury}RZiSJednostkaOp"/>
 *           &lt;element name="RZiSJednostkaInna" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaStruktury}RZiSJednostkaInna"/>
 *         &lt;/choice>
 *         &lt;element name="ZestZmianWKapitaleJednostkaInna" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaStruktury}ZestZmianWKapitaleJednostkaInna" minOccurs="0"/>
 *         &lt;element name="RachPrzeplywow" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaStruktury}RachPrzeplywowJednostkaInna" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="InformacjaDodatkowaJednostkaOp">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="InformacjaDodatkowa" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowa" maxOccurs="unbounded"/>
 *                     &lt;element name="InformacjaDodatkowaDotyczacaPodatkuDochodowego" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowaDotyczacaPodatkuDochodowego" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="DodatkoweInformacjeIObjasnieniaJednostkaInna">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="DodatkoweInformacjeIObjasnienia" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowa" maxOccurs="unbounded"/>
 *                     &lt;element name="InformacjaDodatkowaDotyczacaPodatkuDochodowego" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowaDotyczacaPodatkuDochodowego" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naglowek",
    "wprowadzenieDoSprawozdaniaFinansowegoJednostkaOp",
    "wprowadzenieDoSprawozdaniaFinansowegoJednostkaInna",
    "bilansJednostkaOp",
    "bilansJednostkaInna",
    "rZiSJednostkaOp",
    "rZiSJednostkaInna",
    "zestZmianWKapitaleJednostkaInna",
    "rachPrzeplywow",
    "informacjaDodatkowaJednostkaOp",
    "dodatkoweInformacjeIObjasnieniaJednostkaInna"
})
@XmlRootElement(name = "JednostkaOp", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
public class JednostkaOp {

    @XmlElement(name = "Naglowek", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
    protected TNaglowekSprawozdaniaFinansowegoOpWZlotych naglowek;
    @XmlElement(name = "WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp wprowadzenieDoSprawozdaniaFinansowegoJednostkaOp;
    @XmlElement(name = "WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna wprowadzenieDoSprawozdaniaFinansowegoJednostkaInna;
    @XmlElement(name = "BilansJednostkaOp", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected BilansJednostkaOp bilansJednostkaOp;
    @XmlElement(name = "BilansJednostkaInna", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected BilansJednostkaInna bilansJednostkaInna;
    @XmlElement(name = "RZiSJednostkaOp", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected RZiSJednostkaOp rZiSJednostkaOp;
    @XmlElement(name = "RZiSJednostkaInna", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected RZiSJednostkaInna rZiSJednostkaInna;
    @XmlElement(name = "ZestZmianWKapitaleJednostkaInna", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected ZestZmianWKapitaleJednostkaInna zestZmianWKapitaleJednostkaInna;
    @XmlElement(name = "RachPrzeplywow", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected RachPrzeplywowJednostkaInna rachPrzeplywow;
    @XmlElement(name = "InformacjaDodatkowaJednostkaOp", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected JednostkaOp.InformacjaDodatkowaJednostkaOp informacjaDodatkowaJednostkaOp;
    @XmlElement(name = "DodatkoweInformacjeIObjasnieniaJednostkaInna", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
    protected JednostkaOp.DodatkoweInformacjeIObjasnieniaJednostkaInna dodatkoweInformacjeIObjasnieniaJednostkaInna;

    /**
     * Gets the value of the naglowek property.
     * 
     * @return
     *     possible object is
     *     {@link TNaglowekSprawozdaniaFinansowegoOpWZlotych }
     *     
     */
    public TNaglowekSprawozdaniaFinansowegoOpWZlotych getNaglowek() {
        return naglowek;
    }

    /**
     * Sets the value of the naglowek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNaglowekSprawozdaniaFinansowegoOpWZlotych }
     *     
     */
    public void setNaglowek(TNaglowekSprawozdaniaFinansowegoOpWZlotych value) {
        this.naglowek = value;
    }

    /**
     * Gets the value of the wprowadzenieDoSprawozdaniaFinansowegoJednostkaOp property.
     * 
     * @return
     *     possible object is
     *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp }
     *     
     */
    public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp getWprowadzenieDoSprawozdaniaFinansowegoJednostkaOp() {
        return wprowadzenieDoSprawozdaniaFinansowegoJednostkaOp;
    }

    /**
     * Sets the value of the wprowadzenieDoSprawozdaniaFinansowegoJednostkaOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp }
     *     
     */
    public void setWprowadzenieDoSprawozdaniaFinansowegoJednostkaOp(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp value) {
        this.wprowadzenieDoSprawozdaniaFinansowegoJednostkaOp = value;
    }

    /**
     * Gets the value of the wprowadzenieDoSprawozdaniaFinansowegoJednostkaInna property.
     * 
     * @return
     *     possible object is
     *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna }
     *     
     */
    public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna getWprowadzenieDoSprawozdaniaFinansowegoJednostkaInna() {
        return wprowadzenieDoSprawozdaniaFinansowegoJednostkaInna;
    }

    /**
     * Sets the value of the wprowadzenieDoSprawozdaniaFinansowegoJednostkaInna property.
     * 
     * @param value
     *     allowed object is
     *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna }
     *     
     */
    public void setWprowadzenieDoSprawozdaniaFinansowegoJednostkaInna(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna value) {
        this.wprowadzenieDoSprawozdaniaFinansowegoJednostkaInna = value;
    }

    /**
     * Gets the value of the bilansJednostkaOp property.
     * 
     * @return
     *     possible object is
     *     {@link BilansJednostkaOp }
     *     
     */
    public BilansJednostkaOp getBilansJednostkaOp() {
        return bilansJednostkaOp;
    }

    /**
     * Sets the value of the bilansJednostkaOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BilansJednostkaOp }
     *     
     */
    public void setBilansJednostkaOp(BilansJednostkaOp value) {
        this.bilansJednostkaOp = value;
    }

    /**
     * Gets the value of the bilansJednostkaInna property.
     * 
     * @return
     *     possible object is
     *     {@link BilansJednostkaInna }
     *     
     */
    public BilansJednostkaInna getBilansJednostkaInna() {
        return bilansJednostkaInna;
    }

    /**
     * Sets the value of the bilansJednostkaInna property.
     * 
     * @param value
     *     allowed object is
     *     {@link BilansJednostkaInna }
     *     
     */
    public void setBilansJednostkaInna(BilansJednostkaInna value) {
        this.bilansJednostkaInna = value;
    }

    /**
     * Gets the value of the rZiSJednostkaOp property.
     * 
     * @return
     *     possible object is
     *     {@link RZiSJednostkaOp }
     *     
     */
    public RZiSJednostkaOp getRZiSJednostkaOp() {
        return rZiSJednostkaOp;
    }

    /**
     * Sets the value of the rZiSJednostkaOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RZiSJednostkaOp }
     *     
     */
    public void setRZiSJednostkaOp(RZiSJednostkaOp value) {
        this.rZiSJednostkaOp = value;
    }

    /**
     * Gets the value of the rZiSJednostkaInna property.
     * 
     * @return
     *     possible object is
     *     {@link RZiSJednostkaInna }
     *     
     */
    public RZiSJednostkaInna getRZiSJednostkaInna() {
        return rZiSJednostkaInna;
    }

    /**
     * Sets the value of the rZiSJednostkaInna property.
     * 
     * @param value
     *     allowed object is
     *     {@link RZiSJednostkaInna }
     *     
     */
    public void setRZiSJednostkaInna(RZiSJednostkaInna value) {
        this.rZiSJednostkaInna = value;
    }

    /**
     * Gets the value of the zestZmianWKapitaleJednostkaInna property.
     * 
     * @return
     *     possible object is
     *     {@link ZestZmianWKapitaleJednostkaInna }
     *     
     */
    public ZestZmianWKapitaleJednostkaInna getZestZmianWKapitaleJednostkaInna() {
        return zestZmianWKapitaleJednostkaInna;
    }

    /**
     * Sets the value of the zestZmianWKapitaleJednostkaInna property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZestZmianWKapitaleJednostkaInna }
     *     
     */
    public void setZestZmianWKapitaleJednostkaInna(ZestZmianWKapitaleJednostkaInna value) {
        this.zestZmianWKapitaleJednostkaInna = value;
    }

    /**
     * Gets the value of the rachPrzeplywow property.
     * 
     * @return
     *     possible object is
     *     {@link RachPrzeplywowJednostkaInna }
     *     
     */
    public RachPrzeplywowJednostkaInna getRachPrzeplywow() {
        return rachPrzeplywow;
    }

    /**
     * Sets the value of the rachPrzeplywow property.
     * 
     * @param value
     *     allowed object is
     *     {@link RachPrzeplywowJednostkaInna }
     *     
     */
    public void setRachPrzeplywow(RachPrzeplywowJednostkaInna value) {
        this.rachPrzeplywow = value;
    }

    /**
     * Gets the value of the informacjaDodatkowaJednostkaOp property.
     * 
     * @return
     *     possible object is
     *     {@link JednostkaOp.InformacjaDodatkowaJednostkaOp }
     *     
     */
    public JednostkaOp.InformacjaDodatkowaJednostkaOp getInformacjaDodatkowaJednostkaOp() {
        return informacjaDodatkowaJednostkaOp;
    }

    /**
     * Sets the value of the informacjaDodatkowaJednostkaOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JednostkaOp.InformacjaDodatkowaJednostkaOp }
     *     
     */
    public void setInformacjaDodatkowaJednostkaOp(JednostkaOp.InformacjaDodatkowaJednostkaOp value) {
        this.informacjaDodatkowaJednostkaOp = value;
    }

    /**
     * Gets the value of the dodatkoweInformacjeIObjasnieniaJednostkaInna property.
     * 
     * @return
     *     possible object is
     *     {@link JednostkaOp.DodatkoweInformacjeIObjasnieniaJednostkaInna }
     *     
     */
    public JednostkaOp.DodatkoweInformacjeIObjasnieniaJednostkaInna getDodatkoweInformacjeIObjasnieniaJednostkaInna() {
        return dodatkoweInformacjeIObjasnieniaJednostkaInna;
    }

    /**
     * Sets the value of the dodatkoweInformacjeIObjasnieniaJednostkaInna property.
     * 
     * @param value
     *     allowed object is
     *     {@link JednostkaOp.DodatkoweInformacjeIObjasnieniaJednostkaInna }
     *     
     */
    public void setDodatkoweInformacjeIObjasnieniaJednostkaInna(JednostkaOp.DodatkoweInformacjeIObjasnieniaJednostkaInna value) {
        this.dodatkoweInformacjeIObjasnieniaJednostkaInna = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DodatkoweInformacjeIObjasnienia" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowa" maxOccurs="unbounded"/>
     *         &lt;element name="InformacjaDodatkowaDotyczacaPodatkuDochodowego" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowaDotyczacaPodatkuDochodowego" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dodatkoweInformacjeIObjasnienia",
        "informacjaDodatkowaDotyczacaPodatkuDochodowego"
    })
    public static class DodatkoweInformacjeIObjasnieniaJednostkaInna {

        @XmlElement(name = "DodatkoweInformacjeIObjasnienia", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected List<TInformacjaDodatkowa> dodatkoweInformacjeIObjasnienia;
        @XmlElement(name = "InformacjaDodatkowaDotyczacaPodatkuDochodowego", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected TInformacjaDodatkowaDotyczacaPodatkuDochodowego informacjaDodatkowaDotyczacaPodatkuDochodowego;

        /**
         * Gets the value of the dodatkoweInformacjeIObjasnienia property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dodatkoweInformacjeIObjasnienia property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDodatkoweInformacjeIObjasnienia().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TInformacjaDodatkowa }
         * 
         * 
         */
        public List<TInformacjaDodatkowa> getDodatkoweInformacjeIObjasnienia() {
            if (dodatkoweInformacjeIObjasnienia == null) {
                dodatkoweInformacjeIObjasnienia = new ArrayList<TInformacjaDodatkowa>();
            }
            return this.dodatkoweInformacjeIObjasnienia;
        }

        /**
         * Gets the value of the informacjaDodatkowaDotyczacaPodatkuDochodowego property.
         * 
         * @return
         *     possible object is
         *     {@link TInformacjaDodatkowaDotyczacaPodatkuDochodowego }
         *     
         */
        public TInformacjaDodatkowaDotyczacaPodatkuDochodowego getInformacjaDodatkowaDotyczacaPodatkuDochodowego() {
            return informacjaDodatkowaDotyczacaPodatkuDochodowego;
        }

        /**
         * Sets the value of the informacjaDodatkowaDotyczacaPodatkuDochodowego property.
         * 
         * @param value
         *     allowed object is
         *     {@link TInformacjaDodatkowaDotyczacaPodatkuDochodowego }
         *     
         */
        public void setInformacjaDodatkowaDotyczacaPodatkuDochodowego(TInformacjaDodatkowaDotyczacaPodatkuDochodowego value) {
            this.informacjaDodatkowaDotyczacaPodatkuDochodowego = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InformacjaDodatkowa" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowa" maxOccurs="unbounded"/>
     *         &lt;element name="InformacjaDodatkowaDotyczacaPodatkuDochodowego" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TInformacjaDodatkowaDotyczacaPodatkuDochodowego" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "informacjaDodatkowa",
        "informacjaDodatkowaDotyczacaPodatkuDochodowego"
    })
    public static class InformacjaDodatkowaJednostkaOp {

        @XmlElement(name = "InformacjaDodatkowa", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected List<TInformacjaDodatkowa> informacjaDodatkowa;
        @XmlElement(name = "InformacjaDodatkowaDotyczacaPodatkuDochodowego", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected TInformacjaDodatkowaDotyczacaPodatkuDochodowego informacjaDodatkowaDotyczacaPodatkuDochodowego;

        /**
         * Gets the value of the informacjaDodatkowa property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the informacjaDodatkowa property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInformacjaDodatkowa().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TInformacjaDodatkowa }
         * 
         * 
         */
        public List<TInformacjaDodatkowa> getInformacjaDodatkowa() {
            if (informacjaDodatkowa == null) {
                informacjaDodatkowa = new ArrayList<TInformacjaDodatkowa>();
            }
            return this.informacjaDodatkowa;
        }

        /**
         * Gets the value of the informacjaDodatkowaDotyczacaPodatkuDochodowego property.
         * 
         * @return
         *     possible object is
         *     {@link TInformacjaDodatkowaDotyczacaPodatkuDochodowego }
         *     
         */
        public TInformacjaDodatkowaDotyczacaPodatkuDochodowego getInformacjaDodatkowaDotyczacaPodatkuDochodowego() {
            return informacjaDodatkowaDotyczacaPodatkuDochodowego;
        }

        /**
         * Sets the value of the informacjaDodatkowaDotyczacaPodatkuDochodowego property.
         * 
         * @param value
         *     allowed object is
         *     {@link TInformacjaDodatkowaDotyczacaPodatkuDochodowego }
         *     
         */
        public void setInformacjaDodatkowaDotyczacaPodatkuDochodowego(TInformacjaDodatkowaDotyczacaPodatkuDochodowego value) {
            this.informacjaDodatkowaDotyczacaPodatkuDochodowego = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="P_1">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_1A" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaSiedziba"/>
     *                   &lt;element name="P_1B" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TAdresZOpcZagranicznym"/>
     *                   &lt;element name="P_1C" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}PKDPodstawowaDzialalnosc"/>
     *                   &lt;element name="P_1D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
     *                   &lt;element name="P_1E" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrKRS" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_2" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatOpcjonalnych" minOccurs="0"/>
     *         &lt;element name="P_3" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatSF"/>
     *         &lt;element name="P_4" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="P_5">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_5A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="P_5B" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="P_5C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_6" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_6A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="P_6B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_7">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_7A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
     *                   &lt;element name="P_7B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
     *                   &lt;element name="P_7C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
     *                   &lt;element name="P_7D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_8" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TPozycjaUzytkownika" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p1",
        "p2",
        "p3",
        "p4",
        "p5",
        "p6",
        "p7",
        "p8"
    })
    public static class WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna {

        @XmlElement(name = "P_1", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P1 p1;
        @XmlElement(name = "P_2", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected TZakresDatOpcjonalnych p2;
        @XmlElement(name = "P_3", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected TZakresDatSF p3;
        @XmlElement(name = "P_4", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected boolean p4;
        @XmlElement(name = "P_5", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P5 p5;
        @XmlElement(name = "P_6", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P6 p6;
        @XmlElement(name = "P_7", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P7 p7;
        @XmlElement(name = "P_8", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected List<TPozycjaUzytkownika> p8;

        /**
         * Gets the value of the p1 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P1 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P1 getP1() {
            return p1;
        }

        /**
         * Sets the value of the p1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P1 }
         *     
         */
        public void setP1(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P1 value) {
            this.p1 = value;
        }

        /**
         * Gets the value of the p2 property.
         * 
         * @return
         *     possible object is
         *     {@link TZakresDatOpcjonalnych }
         *     
         */
        public TZakresDatOpcjonalnych getP2() {
            return p2;
        }

        /**
         * Sets the value of the p2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link TZakresDatOpcjonalnych }
         *     
         */
        public void setP2(TZakresDatOpcjonalnych value) {
            this.p2 = value;
        }

        /**
         * Gets the value of the p3 property.
         * 
         * @return
         *     possible object is
         *     {@link TZakresDatSF }
         *     
         */
        public TZakresDatSF getP3() {
            return p3;
        }

        /**
         * Sets the value of the p3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link TZakresDatSF }
         *     
         */
        public void setP3(TZakresDatSF value) {
            this.p3 = value;
        }

        /**
         * Gets the value of the p4 property.
         * 
         */
        public boolean isP4() {
            return p4;
        }

        /**
         * Sets the value of the p4 property.
         * 
         */
        public void setP4(boolean value) {
            this.p4 = value;
        }

        /**
         * Gets the value of the p5 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P5 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P5 getP5() {
            return p5;
        }

        /**
         * Sets the value of the p5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P5 }
         *     
         */
        public void setP5(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P5 value) {
            this.p5 = value;
        }

        /**
         * Gets the value of the p6 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P6 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P6 getP6() {
            return p6;
        }

        /**
         * Sets the value of the p6 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P6 }
         *     
         */
        public void setP6(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P6 value) {
            this.p6 = value;
        }

        /**
         * Gets the value of the p7 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P7 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P7 getP7() {
            return p7;
        }

        /**
         * Sets the value of the p7 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P7 }
         *     
         */
        public void setP7(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaInna.P7 value) {
            this.p7 = value;
        }

        /**
         * Gets the value of the p8 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p8 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP8().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPozycjaUzytkownika }
         * 
         * 
         */
        public List<TPozycjaUzytkownika> getP8() {
            if (p8 == null) {
                p8 = new ArrayList<TPozycjaUzytkownika>();
            }
            return this.p8;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_1A" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaSiedziba"/>
         *         &lt;element name="P_1B" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TAdresZOpcZagranicznym"/>
         *         &lt;element name="P_1C" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}PKDPodstawowaDzialalnosc"/>
         *         &lt;element name="P_1D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
         *         &lt;element name="P_1E" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrKRS" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p1A",
            "p1B",
            "p1C",
            "p1D",
            "p1E"
        })
        public static class P1 {

            @XmlElement(name = "P_1A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected TNazwaSiedziba p1A;
            @XmlElement(name = "P_1B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected TAdresZOpcZagranicznym p1B;
            @XmlElement(name = "P_1C", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected PKDPodstawowaDzialalnosc p1C;
            @XmlElement(name = "P_1D", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected String p1D;
            @XmlElement(name = "P_1E", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected String p1E;

            /**
             * Gets the value of the p1A property.
             * 
             * @return
             *     possible object is
             *     {@link TNazwaSiedziba }
             *     
             */
            public TNazwaSiedziba getP1A() {
                return p1A;
            }

            /**
             * Sets the value of the p1A property.
             * 
             * @param value
             *     allowed object is
             *     {@link TNazwaSiedziba }
             *     
             */
            public void setP1A(TNazwaSiedziba value) {
                this.p1A = value;
            }

            /**
             * Gets the value of the p1B property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresZOpcZagranicznym }
             *     
             */
            public TAdresZOpcZagranicznym getP1B() {
                return p1B;
            }

            /**
             * Sets the value of the p1B property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresZOpcZagranicznym }
             *     
             */
            public void setP1B(TAdresZOpcZagranicznym value) {
                this.p1B = value;
            }

            /**
             * Gets the value of the p1C property.
             * 
             * @return
             *     possible object is
             *     {@link PKDPodstawowaDzialalnosc }
             *     
             */
            public PKDPodstawowaDzialalnosc getP1C() {
                return p1C;
            }

            /**
             * Sets the value of the p1C property.
             * 
             * @param value
             *     allowed object is
             *     {@link PKDPodstawowaDzialalnosc }
             *     
             */
            public void setP1C(PKDPodstawowaDzialalnosc value) {
                this.p1C = value;
            }

            /**
             * Gets the value of the p1D property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP1D() {
                return p1D;
            }

            /**
             * Sets the value of the p1D property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP1D(String value) {
                this.p1D = value;
            }

            /**
             * Gets the value of the p1E property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP1E() {
                return p1E;
            }

            /**
             * Sets the value of the p1E property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP1E(String value) {
                this.p1E = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_5A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="P_5B" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="P_5C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p5A",
            "p5B",
            "p5C"
        })
        public static class P5 {

            @XmlElement(name = "P_5A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected boolean p5A;
            @XmlElement(name = "P_5B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected boolean p5B;
            @XmlElement(name = "P_5C", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected String p5C;

            /**
             * Gets the value of the p5A property.
             * 
             */
            public boolean isP5A() {
                return p5A;
            }

            /**
             * Sets the value of the p5A property.
             * 
             */
            public void setP5A(boolean value) {
                this.p5A = value;
            }

            /**
             * Gets the value of the p5B property.
             * 
             */
            public boolean isP5B() {
                return p5B;
            }

            /**
             * Sets the value of the p5B property.
             * 
             */
            public void setP5B(boolean value) {
                this.p5B = value;
            }

            /**
             * Gets the value of the p5C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP5C() {
                return p5C;
            }

            /**
             * Sets the value of the p5C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP5C(String value) {
                this.p5C = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_6A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="P_6B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p6A",
            "p6B"
        })
        public static class P6 {

            @XmlElement(name = "P_6A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected boolean p6A;
            @XmlElement(name = "P_6B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected String p6B;

            /**
             * Gets the value of the p6A property.
             * 
             */
            public boolean isP6A() {
                return p6A;
            }

            /**
             * Sets the value of the p6A property.
             * 
             */
            public void setP6A(boolean value) {
                this.p6A = value;
            }

            /**
             * Gets the value of the p6B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP6B() {
                return p6B;
            }

            /**
             * Sets the value of the p6B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP6B(String value) {
                this.p6B = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_7A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
         *         &lt;element name="P_7B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
         *         &lt;element name="P_7C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
         *         &lt;element name="P_7D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p7A",
            "p7B",
            "p7C",
            "p7D"
        })
        public static class P7 {

            @XmlElement(name = "P_7A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected List<String> p7A;
            @XmlElement(name = "P_7B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected List<String> p7B;
            @XmlElement(name = "P_7C", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected List<String> p7C;
            @XmlElement(name = "P_7D", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected List<String> p7D;

            /**
             * Gets the value of the p7A property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p7A property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP7A().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP7A() {
                if (p7A == null) {
                    p7A = new ArrayList<String>();
                }
                return this.p7A;
            }

            /**
             * Gets the value of the p7B property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p7B property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP7B().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP7B() {
                if (p7B == null) {
                    p7B = new ArrayList<String>();
                }
                return this.p7B;
            }

            /**
             * Gets the value of the p7C property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p7C property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP7C().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP7C() {
                if (p7C == null) {
                    p7C = new ArrayList<String>();
                }
                return this.p7C;
            }

            /**
             * Gets the value of the p7D property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p7D property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP7D().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP7D() {
                if (p7D == null) {
                    p7D = new ArrayList<String>();
                }
                return this.p7D;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="P_1">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_1A" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaSiedziba"/>
     *                   &lt;element name="P_1B" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TAdresZOpcZagranicznym"/>
     *                   &lt;element name="P_1C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
     *                   &lt;element name="P_1D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrKRS" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_2" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatOpcjonalnych" minOccurs="0"/>
     *         &lt;element name="P_3" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TZakresDatSF"/>
     *         &lt;element name="P_4">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_4A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="P_4B" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="P_4C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_5">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="P_5A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
     *                   &lt;element name="P_5B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
     *                   &lt;element name="P_5C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
     *                   &lt;element name="P_5D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P_6" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TPozycjaUzytkownika" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p1",
        "p2",
        "p3",
        "p4",
        "p5",
        "p6"
    })
    public static class WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp {

        @XmlElement(name = "P_1", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P1 p1;
        @XmlElement(name = "P_2", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected TZakresDatOpcjonalnych p2;
        @XmlElement(name = "P_3", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected TZakresDatSF p3;
        @XmlElement(name = "P_4", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P4 p4;
        @XmlElement(name = "P_5", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
        protected JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P5 p5;
        @XmlElement(name = "P_6", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
        protected List<TPozycjaUzytkownika> p6;

        /**
         * Gets the value of the p1 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P1 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P1 getP1() {
            return p1;
        }

        /**
         * Sets the value of the p1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P1 }
         *     
         */
        public void setP1(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P1 value) {
            this.p1 = value;
        }

        /**
         * Gets the value of the p2 property.
         * 
         * @return
         *     possible object is
         *     {@link TZakresDatOpcjonalnych }
         *     
         */
        public TZakresDatOpcjonalnych getP2() {
            return p2;
        }

        /**
         * Sets the value of the p2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link TZakresDatOpcjonalnych }
         *     
         */
        public void setP2(TZakresDatOpcjonalnych value) {
            this.p2 = value;
        }

        /**
         * Gets the value of the p3 property.
         * 
         * @return
         *     possible object is
         *     {@link TZakresDatSF }
         *     
         */
        public TZakresDatSF getP3() {
            return p3;
        }

        /**
         * Sets the value of the p3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link TZakresDatSF }
         *     
         */
        public void setP3(TZakresDatSF value) {
            this.p3 = value;
        }

        /**
         * Gets the value of the p4 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P4 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P4 getP4() {
            return p4;
        }

        /**
         * Sets the value of the p4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P4 }
         *     
         */
        public void setP4(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P4 value) {
            this.p4 = value;
        }

        /**
         * Gets the value of the p5 property.
         * 
         * @return
         *     possible object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P5 }
         *     
         */
        public JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P5 getP5() {
            return p5;
        }

        /**
         * Sets the value of the p5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P5 }
         *     
         */
        public void setP5(JednostkaOp.WprowadzenieDoSprawozdaniaFinansowegoJednostkaOp.P5 value) {
            this.p5 = value;
        }

        /**
         * Gets the value of the p6 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p6 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP6().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPozycjaUzytkownika }
         * 
         * 
         */
        public List<TPozycjaUzytkownika> getP6() {
            if (p6 == null) {
                p6 = new ArrayList<TPozycjaUzytkownika>();
            }
            return this.p6;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_1A" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaSiedziba"/>
         *         &lt;element name="P_1B" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TAdresZOpcZagranicznym"/>
         *         &lt;element name="P_1C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrNIP"/>
         *         &lt;element name="P_1D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TNrKRS" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p1A",
            "p1B",
            "p1C",
            "p1D"
        })
        public static class P1 {

            @XmlElement(name = "P_1A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected TNazwaSiedziba p1A;
            @XmlElement(name = "P_1B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected TAdresZOpcZagranicznym p1B;
            @XmlElement(name = "P_1C", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected String p1C;
            @XmlElement(name = "P_1D", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected String p1D;

            /**
             * Gets the value of the p1A property.
             * 
             * @return
             *     possible object is
             *     {@link TNazwaSiedziba }
             *     
             */
            public TNazwaSiedziba getP1A() {
                return p1A;
            }

            /**
             * Sets the value of the p1A property.
             * 
             * @param value
             *     allowed object is
             *     {@link TNazwaSiedziba }
             *     
             */
            public void setP1A(TNazwaSiedziba value) {
                this.p1A = value;
            }

            /**
             * Gets the value of the p1B property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresZOpcZagranicznym }
             *     
             */
            public TAdresZOpcZagranicznym getP1B() {
                return p1B;
            }

            /**
             * Sets the value of the p1B property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresZOpcZagranicznym }
             *     
             */
            public void setP1B(TAdresZOpcZagranicznym value) {
                this.p1B = value;
            }

            /**
             * Gets the value of the p1C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP1C() {
                return p1C;
            }

            /**
             * Sets the value of the p1C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP1C(String value) {
                this.p1C = value;
            }

            /**
             * Gets the value of the p1D property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP1D() {
                return p1D;
            }

            /**
             * Sets the value of the p1D property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP1D(String value) {
                this.p1D = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_4A" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="P_4B" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="P_4C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p4A",
            "p4B",
            "p4C"
        })
        public static class P4 {

            @XmlElement(name = "P_4A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected boolean p4A;
            @XmlElement(name = "P_4B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected boolean p4B;
            @XmlElement(name = "P_4C", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected String p4C;

            /**
             * Gets the value of the p4A property.
             * 
             */
            public boolean isP4A() {
                return p4A;
            }

            /**
             * Sets the value of the p4A property.
             * 
             */
            public void setP4A(boolean value) {
                this.p4A = value;
            }

            /**
             * Gets the value of the p4B property.
             * 
             */
            public boolean isP4B() {
                return p4B;
            }

            /**
             * Sets the value of the p4B property.
             * 
             */
            public void setP4B(boolean value) {
                this.p4B = value;
            }

            /**
             * Gets the value of the p4C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP4C() {
                return p4C;
            }

            /**
             * Sets the value of the p4C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP4C(String value) {
                this.p4C = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="P_5A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
         *         &lt;element name="P_5B" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
         *         &lt;element name="P_5C" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded"/>
         *         &lt;element name="P_5D" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TTekstowy" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p5A",
            "p5B",
            "p5C",
            "p5D"
        })
        public static class P5 {

            @XmlElement(name = "P_5A", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected List<String> p5A;
            @XmlElement(name = "P_5B", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected List<String> p5B;
            @XmlElement(name = "P_5C", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych", required = true)
            protected List<String> p5C;
            @XmlElement(name = "P_5D", namespace = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaOrganizacjiPozarzadowejWZlotych")
            protected List<String> p5D;

            /**
             * Gets the value of the p5A property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p5A property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP5A().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP5A() {
                if (p5A == null) {
                    p5A = new ArrayList<String>();
                }
                return this.p5A;
            }

            /**
             * Gets the value of the p5B property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p5B property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP5B().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP5B() {
                if (p5B == null) {
                    p5B = new ArrayList<String>();
                }
                return this.p5B;
            }

            /**
             * Gets the value of the p5C property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p5C property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP5C().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP5C() {
                if (p5C == null) {
                    p5C = new ArrayList<String>();
                }
                return this.p5C;
            }

            /**
             * Gets the value of the p5D property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the p5D property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getP5D().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getP5D() {
                if (p5D == null) {
                    p5D = new ArrayList<String>();
                }
                return this.p5D;
            }

        }

    }

}
