//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 09:13:00 PM CET 
//


package sprawozdania.v12;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Typ pozwalający na rozszerzenie szczegółowości sprawozdania.
 * 
 * <p>Java class for TKwotyPozycjiSprawozdania complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TKwotyPozycjiSprawozdania">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NazwaPozycji" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TNazwaPozycjiUzytkownika"/>
 *         &lt;element name="KwotyPozycji" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TKwotyPozycji"/>
 *         &lt;element name="Podpozycja" type="{http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/}TKwotyPozycjiSprawozdania" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TKwotyPozycjiSprawozdania", propOrder = {
    "nazwaPozycji",
    "kwotyPozycji",
    "podpozycja"
})
public class TKwotyPozycjiSprawozdania {

    @XmlElement(name = "NazwaPozycji", required = true)
    protected String nazwaPozycji;
    @XmlElement(name = "KwotyPozycji", required = true)
    protected TKwotyPozycji kwotyPozycji;
    @XmlElement(name = "Podpozycja")
    protected List<TKwotyPozycjiSprawozdania> podpozycja;

    /**
     * Gets the value of the nazwaPozycji property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwaPozycji() {
        return nazwaPozycji;
    }

    /**
     * Sets the value of the nazwaPozycji property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwaPozycji(String value) {
        this.nazwaPozycji = value;
    }

    /**
     * Gets the value of the kwotyPozycji property.
     * 
     * @return
     *     possible object is
     *     {@link TKwotyPozycji }
     *     
     */
    public TKwotyPozycji getKwotyPozycji() {
        return kwotyPozycji;
    }

    /**
     * Sets the value of the kwotyPozycji property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKwotyPozycji }
     *     
     */
    public void setKwotyPozycji(TKwotyPozycji value) {
        this.kwotyPozycji = value;
    }

    /**
     * Gets the value of the podpozycja property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the podpozycja property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPodpozycja().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TKwotyPozycjiSprawozdania }
     * 
     * 
     */
    public List<TKwotyPozycjiSprawozdania> getPodpozycja() {
        if (podpozycja == null) {
            podpozycja = new ArrayList<TKwotyPozycjiSprawozdania>();
        }
        return this.podpozycja;
    }

}
