//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.24 at 05:42:03 PM CET 
//


package generated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RaportEzla }
     * 
     */
    public RaportEzla createRaportEzla() {
        return new RaportEzla();
    }

    /**
     * Create an instance of {@link RaportEzla.DokumentyEzla }
     * 
     */
    public RaportEzla.DokumentyEzla createRaportEzlaDokumentyEzla() {
        return new RaportEzla.DokumentyEzla();
    }

    /**
     * Create an instance of {@link RaportEzla.DokumentyEzla.DaneDokumentu }
     * 
     */
    public RaportEzla.DokumentyEzla.DaneDokumentu createRaportEzlaDokumentyEzlaDaneDokumentu() {
        return new RaportEzla.DokumentyEzla.DaneDokumentu();
    }

    /**
     * Create an instance of {@link RaportEzla.DokumentyEzla.DaneUbezpieczonego }
     * 
     */
    public RaportEzla.DokumentyEzla.DaneUbezpieczonego createRaportEzlaDokumentyEzlaDaneUbezpieczonego() {
        return new RaportEzla.DokumentyEzla.DaneUbezpieczonego();
    }

    /**
     * Create an instance of {@link RaportEzla.DaneRaportu }
     * 
     */
    public RaportEzla.DaneRaportu createRaportEzlaDaneRaportu() {
        return new RaportEzla.DaneRaportu();
    }

    /**
     * Create an instance of {@link RaportEzla.DaneRaportu.Platnik }
     * 
     */
    public RaportEzla.DaneRaportu.Platnik createRaportEzlaDaneRaportuPlatnik() {
        return new RaportEzla.DaneRaportu.Platnik();
    }

    /**
     * Create an instance of {@link RaportEzla.DokumentyEzla.DaneDokumentu.OkresZwolnienia }
     * 
     */
    public RaportEzla.DokumentyEzla.DaneDokumentu.OkresZwolnienia createRaportEzlaDokumentyEzlaDaneDokumentuOkresZwolnienia() {
        return new RaportEzla.DokumentyEzla.DaneDokumentu.OkresZwolnienia();
    }

    /**
     * Create an instance of {@link RaportEzla.DokumentyEzla.DaneDokumentu.OkresWSzpitalu }
     * 
     */
    public RaportEzla.DokumentyEzla.DaneDokumentu.OkresWSzpitalu createRaportEzlaDokumentyEzlaDaneDokumentuOkresWSzpitalu() {
        return new RaportEzla.DokumentyEzla.DaneDokumentu.OkresWSzpitalu();
    }

    /**
     * Create an instance of {@link RaportEzla.DokumentyEzla.DaneUbezpieczonego.Identyfikator }
     * 
     */
    public RaportEzla.DokumentyEzla.DaneUbezpieczonego.Identyfikator createRaportEzlaDokumentyEzlaDaneUbezpieczonegoIdentyfikator() {
        return new RaportEzla.DokumentyEzla.DaneUbezpieczonego.Identyfikator();
    }

    /**
     * Create an instance of {@link RaportEzla.DaneRaportu.Platnik.Identyfikator }
     * 
     */
    public RaportEzla.DaneRaportu.Platnik.Identyfikator createRaportEzlaDaneRaportuPlatnikIdentyfikator() {
        return new RaportEzla.DaneRaportu.Platnik.Identyfikator();
    }

}
