/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package embeddable;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import javax.faces.bean.SessionScoped;
import javax.inject.Named;
import javax.persistence.Embeddable;

/**
 *
 * @author Osito
 */
@Named
@Embeddable
@SessionScoped
public class Miasta implements Serializable {
    private final static List<String> wykazMiast;
    
static{
    wykazMiast = Collections.synchronizedList(new ArrayList<>());
    wykazMiast.add("Aleksandrów Kujawski");
    wykazMiast.add("Aleksandrów Łódzki");
    wykazMiast.add("Alwernia");
    wykazMiast.add("Andrychów");
    wykazMiast.add("Annopol");
    wykazMiast.add("Augustów");
    wykazMiast.add("Babimost");
    wykazMiast.add("Baborów");
    wykazMiast.add("Baranów Sandomierski");
    wykazMiast.add("Barcin");
    wykazMiast.add("Barczewo");
    wykazMiast.add("Bardo");
    wykazMiast.add("Barlinek");
    wykazMiast.add("Bartoszyce");
    wykazMiast.add("Barwice");
    wykazMiast.add("Bełchatów");
    wykazMiast.add("Bełżyce");
    wykazMiast.add("Będzin");
    wykazMiast.add("Biała");
    wykazMiast.add("Biała Piska");
    wykazMiast.add("Biała Podlaska");
    wykazMiast.add("Biała Rawska");
    wykazMiast.add("Białobrzegi");
    wykazMiast.add("Białogard");
    wykazMiast.add("Biały Bór");
    wykazMiast.add("Białystok");
    wykazMiast.add("Biecz");
    wykazMiast.add("Bielawa");
    wykazMiast.add("Bielsk Podlaski");
    wykazMiast.add("Bielsko-Biała");
    wykazMiast.add("Bieruń");
    wykazMiast.add("Bierutów");
    wykazMiast.add("Bieżuń");
    wykazMiast.add("Biłgoraj");
    wykazMiast.add("Biskupiec");
    wykazMiast.add("Bisztynek");
    wykazMiast.add("Blachownia");
    wykazMiast.add("Błaszki");
    wykazMiast.add("Błażowa");
    wykazMiast.add("Błonie");
    wykazMiast.add("Bobolice");
    wykazMiast.add("Bochnia");
    wykazMiast.add("Bodzentyn");
    wykazMiast.add("Bogatynia");
    wykazMiast.add("Boguszów-Gorce");
    wykazMiast.add("Bojanowo");
    wykazMiast.add("Bolesławiec");
    wykazMiast.add("Bolków");
    wykazMiast.add("Borek Wielkopolski");
    wykazMiast.add("Borne Sulinowo");
    wykazMiast.add("Braniewo");
    wykazMiast.add("Brańsk");
    wykazMiast.add("Brodnica");
    wykazMiast.add("Brok");
    wykazMiast.add("Brusy");
    wykazMiast.add("Brwinów");
    wykazMiast.add("Brzeg");
    wykazMiast.add("Brzeg Dolny");
    wykazMiast.add("Brzesko");
    wykazMiast.add("Brzeszcze");
    wykazMiast.add("Brześć Kujawski");
    wykazMiast.add("Brzeziny");
    wykazMiast.add("Brzozów");
    wykazMiast.add("Buk");
    wykazMiast.add("Bukowno");
    wykazMiast.add("Busko Zdrój");
    wykazMiast.add("Bychawa");
    wykazMiast.add("Byczyna");
    wykazMiast.add("Bydgoszcz");
    wykazMiast.add("Bystrzyca Kłodzka");
    wykazMiast.add("Bytom");
    wykazMiast.add("Bytom Odrzański");
    wykazMiast.add("Bytów");
    wykazMiast.add("Cedynia");
    wykazMiast.add("Chełm");
    wykazMiast.add("Chełmek");
    wykazMiast.add("Chełmno");
    wykazMiast.add("Chełmża");
    wykazMiast.add("Chęciny");
    wykazMiast.add("Chmielnik");
    wykazMiast.add("Chocianów");
    wykazMiast.add("Chociwel");
    wykazMiast.add("Chodecz");
    wykazMiast.add("Chodzież");
    wykazMiast.add("Chojna");
    wykazMiast.add("Chojnice");
    wykazMiast.add("Chojnów");
    wykazMiast.add("Choroszcz");
    wykazMiast.add("Chorzele");
    wykazMiast.add("Chorzów");
    wykazMiast.add("Choszczno");
    wykazMiast.add("Chrzanów");
    wykazMiast.add("Ciechanowiec");
    wykazMiast.add("Ciechanów");
    wykazMiast.add("Ciechocinek");
    wykazMiast.add("Cieszanów");
    wykazMiast.add("Cieszyn");
    wykazMiast.add("Ciężkowice");
    wykazMiast.add("Cybinka");
    wykazMiast.add("Czaplinek");
    wykazMiast.add("Czarna Białostocka");
    wykazMiast.add("Czarna Woda");
    wykazMiast.add("Czarne");
    wykazMiast.add("Czarnków");
    wykazMiast.add("Czchów");
    wykazMiast.add("Czechowice-Dziedzice");
    wykazMiast.add("Czeladź");
    wykazMiast.add("Czempiń");
    wykazMiast.add("Czerniejewo");
    wykazMiast.add("Czersk");
    wykazMiast.add("Czerwieńsk");
    wykazMiast.add("Czerwionka-Leszczyny");
    wykazMiast.add("Częstochowa");
    wykazMiast.add("Człopa");
    wykazMiast.add("Człuchów");
    wykazMiast.add("Ćmielów");
    wykazMiast.add("Darłowo");
    wykazMiast.add("Dąbie");
    wykazMiast.add("Dąbrowa Białostocka");
    wykazMiast.add("Dąbrowa Górnicza");
    wykazMiast.add("Dąbrowa Tarnowska");
    wykazMiast.add("Debrzno");
    wykazMiast.add("Dębica");
    wykazMiast.add("Dęblin");
    wykazMiast.add("Dębno");
    wykazMiast.add("Dobczyce");
    wykazMiast.add("Dobiegniew");
    wykazMiast.add("Dobra");
    wykazMiast.add("Dobra");
    wykazMiast.add("Dobre Miasto");
    wykazMiast.add("Dobrodzień");
    wykazMiast.add("Dobrzany");
    wykazMiast.add("Dobrzyń nad Wisłą");
    wykazMiast.add("Dolsk");
    wykazMiast.add("Drawno");
    wykazMiast.add("Drawsko Pomorskie");
    wykazMiast.add("Drezdenko");
    wykazMiast.add("Drobin");
    wykazMiast.add("Drohiczyn");
    wykazMiast.add("Drzewica");
    wykazMiast.add("Dukla");
    wykazMiast.add("Duszniki Zdrój");
    wykazMiast.add("Dynów");
    wykazMiast.add("Działdowo");
    wykazMiast.add("Działoszyce");
    wykazMiast.add("Działoszyn");
    wykazMiast.add("Dzierzgoń");
    wykazMiast.add("Dzierżoniów");
    wykazMiast.add("Elbląg");
    wykazMiast.add("Ełk");
    wykazMiast.add("Frampol");
    wykazMiast.add("Frombork");
    wykazMiast.add("Garwolin");
    wykazMiast.add("Gąbin");
    wykazMiast.add("Gdańsk");
    wykazMiast.add("Gdynia");
    wykazMiast.add("Giżycko");
    wykazMiast.add("Glinojeck");
    wykazMiast.add("Gliwice");
    wykazMiast.add("Głogów");
    wykazMiast.add("Głogów Małopolski");
    wykazMiast.add("Głogówek");
    wykazMiast.add("Głowno");
    wykazMiast.add("Głubczyce");
    wykazMiast.add("Głuchołazy");
    wykazMiast.add("Głuszyca");
    wykazMiast.add("Gniew");
    wykazMiast.add("Gniewkowo");
    wykazMiast.add("Gniezno");
    wykazMiast.add("Gogolin");
    wykazMiast.add("Golczewo");
    wykazMiast.add("Goleniów");
    wykazMiast.add("Golina");
    wykazMiast.add("Golub-Dobrzyń");
    wykazMiast.add("Gołańcz");
    wykazMiast.add("Gołdap");
    wykazMiast.add("Goniądz");
    wykazMiast.add("Gorlice");
    wykazMiast.add("Gorzów Śląski");
    wykazMiast.add("Gorzów Wielkopolski");
    wykazMiast.add("Gostynin");
    wykazMiast.add("Gostyń");
    wykazMiast.add("Gozdnica");
    wykazMiast.add("Góra");
    wykazMiast.add("Góra Kalwaria");
    wykazMiast.add("Górowo Iławeckie");
    wykazMiast.add("Górzno");
    wykazMiast.add("Grabów nad Prosną");
    wykazMiast.add("Grajewo");
    wykazMiast.add("Grodków");
    wykazMiast.add("Grodzisk Mazowiecki");
    wykazMiast.add("Grodzisk Wielkopolski");
    wykazMiast.add("Grójec");
    wykazMiast.add("Grudziądz");
    wykazMiast.add("Grybów");
    wykazMiast.add("Gryfice");
    wykazMiast.add("Gryfino");
    wykazMiast.add("Gryfów Śląski");
    wykazMiast.add("Gubin");
    wykazMiast.add("Hajnówka");
    wykazMiast.add("Hel");
    wykazMiast.add("Hrubieszów");
    wykazMiast.add("Iława");
    wykazMiast.add("Iłowa");
    wykazMiast.add("Iłża");
    wykazMiast.add("Imielin");
    wykazMiast.add("Inowrocław");
    wykazMiast.add("Ińsko");
    wykazMiast.add("Iwonicz Zdrój");
    wykazMiast.add("Izbica Kujawska");
    wykazMiast.add("Jabłonowo Pomorskie");
    wykazMiast.add("Janikowo");
    wykazMiast.add("Janowiec Wielkopolski");
    wykazMiast.add("Janów Lubelski");
    wykazMiast.add("Jarocin");
    wykazMiast.add("Jarosław");
    wykazMiast.add("Jasień");
    wykazMiast.add("Jasło");
    wykazMiast.add("Jastarnia");
    wykazMiast.add("Jastrowie");
    wykazMiast.add("Jastrzębie Zdrój");
    wykazMiast.add("Jawor");
    wykazMiast.add("Jaworzno");
    wykazMiast.add("Jaworzyna Śląska");
    wykazMiast.add("Jedlicze");
    wykazMiast.add("Jedlina Zdrój");
    wykazMiast.add("Jedwabne");
    wykazMiast.add("Jelcz-Laskowice");
    wykazMiast.add("Jelenia Góra");
    wykazMiast.add("Jeziorany");
    wykazMiast.add("Jędrzejów");
    wykazMiast.add("Jordanów");
    wykazMiast.add("Józefów");
    wykazMiast.add("Józefów");
    wykazMiast.add("Jutrosin");
    wykazMiast.add("Kalety");
    wykazMiast.add("Kalisz");
    wykazMiast.add("Kalisz Pomorski");
    wykazMiast.add("Kalwaria Zebrzydowska");
    wykazMiast.add("Kałuszyn");
    wykazMiast.add("Kamienna Góra");
    wykazMiast.add("Kamień Krajeński");
    wykazMiast.add("Kamień Pomorski");
    wykazMiast.add("Kamieńsk");
    wykazMiast.add("Kańczuga");
    wykazMiast.add("Karczew");
    wykazMiast.add("Kargowa");
    wykazMiast.add("Karlino");
    wykazMiast.add("Karpacz");
    wykazMiast.add("Kartuzy");
    wykazMiast.add("Katowice");
    wykazMiast.add("Kazimierz Dolny");
    wykazMiast.add("Kazimierza Wielka");
    wykazMiast.add("Kąty Wrocławskie");
    wykazMiast.add("Kcynia");
    wykazMiast.add("Kędzierzyn-Koźle");
    wykazMiast.add("Kępice");
    wykazMiast.add("Kępno");
    wykazMiast.add("Kętrzyn");
    wykazMiast.add("Kęty");
    wykazMiast.add("Kielce");
    wykazMiast.add("Kietrz");
    wykazMiast.add("Kisielice");
    wykazMiast.add("Kleczew");
    wykazMiast.add("Kleszczele");
    wykazMiast.add("Kluczbork");
    wykazMiast.add("Kłecko");
    wykazMiast.add("Kłobuck");
    wykazMiast.add("Kłodawa");
    wykazMiast.add("Kłodzko");
    wykazMiast.add("Knurów");
    wykazMiast.add("Knyszyn");
    wykazMiast.add("Kobylin");
    wykazMiast.add("Kobyłka");
    wykazMiast.add("Kock");
    wykazMiast.add("Kolbuszowa");
    wykazMiast.add("Kolno");
    wykazMiast.add("Kolonowskie");
    wykazMiast.add("Koluszki");
    wykazMiast.add("Koło");
    wykazMiast.add("Kołobrzeg");
    wykazMiast.add("Koniecpol");
    wykazMiast.add("Konin");
    wykazMiast.add("Konstancin-Jeziorna");
    wykazMiast.add("Konstantynów Łódzki");
    wykazMiast.add("Końskie");
    wykazMiast.add("Korfantów");
    wykazMiast.add("Koronowo");
    wykazMiast.add("Korsze");
    wykazMiast.add("Kosów Lacki");
    wykazMiast.add("Kostrzyn");
    wykazMiast.add("Kostrzyn");
    wykazMiast.add("Koszalin");
    wykazMiast.add("Kościan");
    wykazMiast.add("Kościerzyna");
    wykazMiast.add("Kowal");
    wykazMiast.add("Kowalewo Pomorskie");
    wykazMiast.add("Kowary");
    wykazMiast.add("Koziegłowy");
    wykazMiast.add("Kozienice");
    wykazMiast.add("Koźmin Wielkopolski");
    wykazMiast.add("Kożuchów");
    wykazMiast.add("Kórnik");
    wykazMiast.add("Krajenka");
    wykazMiast.add("Kraków");
    wykazMiast.add("Krapkowice");
    wykazMiast.add("Krasnobród");
    wykazMiast.add("Krasnystaw");
    wykazMiast.add("Kraśnik");
    wykazMiast.add("Krobia");
    wykazMiast.add("Krosno");
    wykazMiast.add("Krosno Odrzańskie");
    wykazMiast.add("Krośniewice");
    wykazMiast.add("Krotoszyn");
    wykazMiast.add("Kruszwica");
    wykazMiast.add("Krynica");
    wykazMiast.add("Krynica Morska");
    wykazMiast.add("Krzepice");
    wykazMiast.add("Krzeszowice");
    wykazMiast.add("Krzywiń");
    wykazMiast.add("Krzyż Wielkopolski");
    wykazMiast.add("Książ Wielkopolski");
    wykazMiast.add("Kudowa Zdrój");
    wykazMiast.add("Kunów");
    wykazMiast.add("Kutno");
    wykazMiast.add("Kuźnia Raciborska");
    wykazMiast.add("Kwidzyn");
    wykazMiast.add("Lądek Zdrój");
    wykazMiast.add("Legionowo");
    wykazMiast.add("Legnica");
    wykazMiast.add("Lesko");
    wykazMiast.add("Leszno");
    wykazMiast.add("Leśna");
    wykazMiast.add("Leśnica");
    wykazMiast.add("Lewin Brzeski");
    wykazMiast.add("Leżajsk");
    wykazMiast.add("Lębork");
    wykazMiast.add("Lędziny");
    wykazMiast.add("Libiąż");
    wykazMiast.add("Lidzbark");
    wykazMiast.add("Lidzbark Warmiński");
    wykazMiast.add("Limanowa");
    wykazMiast.add("Lipiany");
    wykazMiast.add("Lipno");
    wykazMiast.add("Lipsk");
    wykazMiast.add("Lipsko");
    wykazMiast.add("Lubaczów");
    wykazMiast.add("Lubań");
    wykazMiast.add("Lubartów");
    wykazMiast.add("Lubawa");
    wykazMiast.add("Lubawka");
    wykazMiast.add("Lubień Kujawski");
    wykazMiast.add("Lubin");
    wykazMiast.add("Lublin");
    wykazMiast.add("Lubliniec");
    wykazMiast.add("Lubniewice");
    wykazMiast.add("Lubomierz");
    wykazMiast.add("Luboń");
    wykazMiast.add("Lubraniec");
    wykazMiast.add("Lubsko");
    wykazMiast.add("Lwówek");
    wykazMiast.add("Lwówek Śląski");
    wykazMiast.add("Łabiszyn");
    wykazMiast.add("Łańcut");
    wykazMiast.add("Łapy");
    wykazMiast.add("Łasin");
    wykazMiast.add("Łask");
    wykazMiast.add("Łaskarzew");
    wykazMiast.add("Łaziska Górne");
    wykazMiast.add("Łazy");
    wykazMiast.add("Łeba");
    wykazMiast.add("Łęczna");
    wykazMiast.add("Łęczyca");
    wykazMiast.add("Łęknica");
    wykazMiast.add("Łobez");
    wykazMiast.add("Łobżenica");
    wykazMiast.add("Łochów");
    wykazMiast.add("Łomianki");
    wykazMiast.add("Łomża");
    wykazMiast.add("Łosice");
    wykazMiast.add("Łowicz");
    wykazMiast.add("Łódź");
    wykazMiast.add("Łuków");
    wykazMiast.add("Maków Mazowiecki");
    wykazMiast.add("Maków Podhalański");
    wykazMiast.add("Malbork");
    wykazMiast.add("Małogoszcz");
    wykazMiast.add("Małomice");
    wykazMiast.add("Margonin");
    wykazMiast.add("Marki");
    wykazMiast.add("Maszewo");
    wykazMiast.add("Miasteczko Śląskie");
    wykazMiast.add("Miastko");
    wykazMiast.add("Miechów");
    wykazMiast.add("Miejska Górka");
    wykazMiast.add("Mielec");
    wykazMiast.add("Mieroszów");
    wykazMiast.add("Mieszkowice");
    wykazMiast.add("Międzybórz");
    wykazMiast.add("Międzychód");
    wykazMiast.add("Międzylesie");
    wykazMiast.add("Międzyrzec Podlaski");
    wykazMiast.add("Międzyrzecz");
    wykazMiast.add("Międzyzdroje");
    wykazMiast.add("Mikołajki");
    wykazMiast.add("Mikołów");
    wykazMiast.add("Mikstat");
    wykazMiast.add("Milanówek");
    wykazMiast.add("Milicz");
    wykazMiast.add("Miłakowo");
    wykazMiast.add("Miłomłyn");
    wykazMiast.add("Miłosław");
    wykazMiast.add("Mińsk Mazowiecki");
    wykazMiast.add("Mirosławiec");
    wykazMiast.add("Mirsk");
    wykazMiast.add("Mława");
    wykazMiast.add("Młynary");
    wykazMiast.add("Mogielnica");
    wykazMiast.add("Mogilno");
    wykazMiast.add("Mońki");
    wykazMiast.add("Morąg");
    wykazMiast.add("Mordy");
    wykazMiast.add("Moryń");
    wykazMiast.add("Mosina");
    wykazMiast.add("Mrągowo");
    wykazMiast.add("Mrocza");
    wykazMiast.add("Mszana Dolna");
    wykazMiast.add("Mszczonów");
    wykazMiast.add("Murowana Goślina");
    wykazMiast.add("Muszyna");
    wykazMiast.add("Mysłowice");
    wykazMiast.add("Myszków");
    wykazMiast.add("Myszyniec");
    wykazMiast.add("Myślenice");
    wykazMiast.add("Myślibórz");
    wykazMiast.add("Nakło nad Notecią");
    wykazMiast.add("Nałęczów");
    wykazMiast.add("Namysłów");
    wykazMiast.add("Narol");
    wykazMiast.add("Nasielsk");
    wykazMiast.add("Nekla");
    wykazMiast.add("Nidzica");
    wykazMiast.add("Niemcza");
    wykazMiast.add("Niemodlin");
    wykazMiast.add("Niepołomice");
    wykazMiast.add("Nieszawa");
    wykazMiast.add("Nisko");
    wykazMiast.add("Nowa Dęba");
    wykazMiast.add("Nowa Ruda");
    wykazMiast.add("Nowa Sarzyna");
    wykazMiast.add("Nowa Sól");
    wykazMiast.add("Nowe");
    wykazMiast.add("Nowe Miasteczko");
    wykazMiast.add("Nowe Miasto Lubawskie");
    wykazMiast.add("Nowe Miasto nad Pilicą");
    wykazMiast.add("Nowe Skalmierzyce");
    wykazMiast.add("Nowe Warpno");
    wykazMiast.add("Nowogard");
    wykazMiast.add("Nowogrodziec");
    wykazMiast.add("Nowogród");
    wykazMiast.add("Nowogród Bobrzański");
    wykazMiast.add("Nowy Dwór Gdański");
    wykazMiast.add("Nowy Dwór Mazowiecki");
    wykazMiast.add("Nowy Sącz");
    wykazMiast.add("Nowy Staw");
    wykazMiast.add("Nowy Targ");
    wykazMiast.add("Nowy Tomyśl");
    wykazMiast.add("Nowy Wiśnicz");
    wykazMiast.add("Nysa");
    wykazMiast.add("Oborniki");
    wykazMiast.add("Oborniki Śląskie");
    wykazMiast.add("Obrzycko");
    wykazMiast.add("Odolanów");
    wykazMiast.add("Ogrodzieniec");
    wykazMiast.add("Okonek");
    wykazMiast.add("Olecko");
    wykazMiast.add("Olesno");
    wykazMiast.add("Oleszyce");
    wykazMiast.add("Oleśnica");
    wykazMiast.add("Olkusz");
    wykazMiast.add("Olsztyn");
    wykazMiast.add("Olsztynek");
    wykazMiast.add("Oława");
    wykazMiast.add("Opalenica");
    wykazMiast.add("Opatów");
    wykazMiast.add("Opoczno");
    wykazMiast.add("Opole");
    wykazMiast.add("Opole Lubelskie");
    wykazMiast.add("Orneta");
    wykazMiast.add("Orzesze");
    wykazMiast.add("Orzysz");
    wykazMiast.add("Osieczna");
    wykazMiast.add("Osiek");
    wykazMiast.add("Ostrołęka");
    wykazMiast.add("Ostroróg");
    wykazMiast.add("Ostrowiec Świętokrzyski");
    wykazMiast.add("Ostróda");
    wykazMiast.add("Ostrów Lubelski");
    wykazMiast.add("Ostrów Mazowiecka");
    wykazMiast.add("Ostrów Wielkopolski");
    wykazMiast.add("Ostrzeszów");
    wykazMiast.add("Ośno Lubuskie");
    wykazMiast.add("Oświęcim");
    wykazMiast.add("Otmuchów");
    wykazMiast.add("Otwock");
    wykazMiast.add("Ozimek");
    wykazMiast.add("Ozorków");
    wykazMiast.add("Ożarów");
    wykazMiast.add("Ożarów Mazowiecki");
    wykazMiast.add("Pabianice");
    wykazMiast.add("Paczków");
    wykazMiast.add("Pajęczno");
    wykazMiast.add("Pakość");
    wykazMiast.add("Parczew");
    wykazMiast.add("Pasłęk");
    wykazMiast.add("Pasym");
    wykazMiast.add("Pelplin");
    wykazMiast.add("Pełczyce");
    wykazMiast.add("Piaseczno");
    wykazMiast.add("Piaski");
    wykazMiast.add("Piastów");
    wykazMiast.add("Piechowice");
    wykazMiast.add("Piekary Śląskie");
    wykazMiast.add("Pieniężno");
    wykazMiast.add("Pieńsk");
    wykazMiast.add("Pieszyce");
    wykazMiast.add("Pilawa");
    wykazMiast.add("Pilica");
    wykazMiast.add("Pilzno");
    wykazMiast.add("Piła");
    wykazMiast.add("Piława Górna");
    wykazMiast.add("Pińczów");
    wykazMiast.add("Pionki");
    wykazMiast.add("Piotrków Kujawski");
    wykazMiast.add("Piotrków Trybunalski");
    wykazMiast.add("Pisz");
    wykazMiast.add("Piwniczna Zdrój");
    wykazMiast.add("Pleszew");
    wykazMiast.add("Płock");
    wykazMiast.add("Płońsk");
    wykazMiast.add("Płoty");
    wykazMiast.add("Pniewy");
    wykazMiast.add("Pobiedziska");
    wykazMiast.add("Poddębice");
    wykazMiast.add("Podkowa Leśna");
    wykazMiast.add("Pogorzela");
    wykazMiast.add("Polanica Zdrój");
    wykazMiast.add("Polanów");
    wykazMiast.add("Police");
    wykazMiast.add("Polkowice");
    wykazMiast.add("Połaniec");
    wykazMiast.add("Połczyn Zdrój");
    wykazMiast.add("Poniatowa");
    wykazMiast.add("Poniec");
    wykazMiast.add("Poręba");
    wykazMiast.add("Poznań");
    wykazMiast.add("Prabuty");
    wykazMiast.add("Praszka");
    wykazMiast.add("Prochowice");
    wykazMiast.add("Proszowice");
    wykazMiast.add("Prudnik");
    wykazMiast.add("Prusice");
    wykazMiast.add("Pruszcz Gdański");
    wykazMiast.add("Pruszków");
    wykazMiast.add("Przasnysz");
    wykazMiast.add("Przedbórz");
    wykazMiast.add("Przedecz");
    wykazMiast.add("Przemków");
    wykazMiast.add("Przemyśl");
    wykazMiast.add("Przeworsk");
    wykazMiast.add("Przysucha");
    wykazMiast.add("Pszczyna");
    wykazMiast.add("Pszów");
    wykazMiast.add("Puck");
    wykazMiast.add("Puławy");
    wykazMiast.add("Pułtusk");
    wykazMiast.add("Puszczykowo");
    wykazMiast.add("Pyrzyce");
    wykazMiast.add("Pyskowice");
    wykazMiast.add("Pyzdry");
    wykazMiast.add("Rabka");
    wykazMiast.add("Raciąż");
    wykazMiast.add("Racibórz");
    wykazMiast.add("Radków");
    wykazMiast.add("Radlin");
    wykazMiast.add("Radom");
    wykazMiast.add("Radomsko");
    wykazMiast.add("Radomyśl Wielki");
    wykazMiast.add("Radymno");
    wykazMiast.add("Radziejów");
    wykazMiast.add("Radzionków");
    wykazMiast.add("Radzymin");
    wykazMiast.add("Radzyń Chełmiński");
    wykazMiast.add("Radzyń Podlaski");
    wykazMiast.add("Rajgród");
    wykazMiast.add("Rakoniewice");
    wykazMiast.add("Raszków");
    wykazMiast.add("Rawa Mazowiecka");
    wykazMiast.add("Rawicz");
    wykazMiast.add("Recz");
    wykazMiast.add("Reda");
    wykazMiast.add("Rejowiec Fabryczny");
    wykazMiast.add("Resko");
    wykazMiast.add("Reszel");
    wykazMiast.add("Rogoźno");
    wykazMiast.add("Ropczyce");
    wykazMiast.add("Różan");
    wykazMiast.add("Ruciane-Nida");
    wykazMiast.add("Ruda Śląska");
    wykazMiast.add("Rudnik nad Sanem");
    wykazMiast.add("Rumia");
    wykazMiast.add("Rybnik");
    wykazMiast.add("Rychwał");
    wykazMiast.add("Rydułtowy");
    wykazMiast.add("Rydzyna");
    wykazMiast.add("Ryki");
    wykazMiast.add("Rymanów");
    wykazMiast.add("Ryn");
    wykazMiast.add("Rypin");
    wykazMiast.add("Rzepin");
    wykazMiast.add("Rzeszów");
    wykazMiast.add("Sandomierz");
    wykazMiast.add("Sanok");
    wykazMiast.add("Sejny");
    wykazMiast.add("Serock");
    wykazMiast.add("Sędziszów");
    wykazMiast.add("Sędziszów Małopolski");
    wykazMiast.add("Sępopol");
    wykazMiast.add("Sępólno Krajeńskie");
    wykazMiast.add("Sianów");
    wykazMiast.add("Siechnice");
    wykazMiast.add("Siedlce");
    wykazMiast.add("Siemianowice Śląskie");
    wykazMiast.add("Siemiatycze");
    wykazMiast.add("Sieniawa");
    wykazMiast.add("Sieradz");
    wykazMiast.add("Sieraków");
    wykazMiast.add("Sierpc");
    wykazMiast.add("Siewierz");
    wykazMiast.add("Skalbmierz");
    wykazMiast.add("Skała");
    wykazMiast.add("Skarszewy");
    wykazMiast.add("Skaryszew");
    wykazMiast.add("Skarżysko-Kamienna");
    wykazMiast.add("Skawina");
    wykazMiast.add("Skępe");
    wykazMiast.add("Skierniewice");
    wykazMiast.add("Skoczów");
    wykazMiast.add("Skoki");
    wykazMiast.add("Skórcz");
    wykazMiast.add("Skwierzyna");
    wykazMiast.add("Sława");
    wykazMiast.add("Sławków");
    wykazMiast.add("Sławno");
    wykazMiast.add("Słomniki");
    wykazMiast.add("Słubice");
    wykazMiast.add("Słupca");
    wykazMiast.add("Słupsk");
    wykazMiast.add("Sobótka");
    wykazMiast.add("Sochaczew");
    wykazMiast.add("Sokołów Małopolski");
    wykazMiast.add("Sokołów Podlaski");
    wykazMiast.add("Sokółka");
    wykazMiast.add("Solec Kujawski");
    wykazMiast.add("Sompolno");
    wykazMiast.add("Sopot");
    wykazMiast.add("Sosnowiec");
    wykazMiast.add("Sośnicowice");
    wykazMiast.add("Stalowa Wola");
    wykazMiast.add("Starachowice");
    wykazMiast.add("Stargard Szczeciński");
    wykazMiast.add("Starogard Gdański");
    wykazMiast.add("Stary Sącz");
    wykazMiast.add("Staszów");
    wykazMiast.add("Stawiski");
    wykazMiast.add("Stawiszyn");
    wykazMiast.add("Stąporków");
    wykazMiast.add("Stęszew");
    wykazMiast.add("Stoczek Łukowski");
    wykazMiast.add("Stronie Śląskie");
    wykazMiast.add("Strumień");
    wykazMiast.add("Stryków");
    wykazMiast.add("Strzegom");
    wykazMiast.add("Strzelce Krajeńskie");
    wykazMiast.add("Strzelce Opolskie");
    wykazMiast.add("Strzelin");
    wykazMiast.add("Strzelno");
    wykazMiast.add("Strzyżów");
    wykazMiast.add("Sucha Beskidzka");
    wykazMiast.add("Suchań");
    wykazMiast.add("Suchedniów");
    wykazMiast.add("Suchowola");
    wykazMiast.add("Sulechów");
    wykazMiast.add("Sulejów");
    wykazMiast.add("Sulejówek");
    wykazMiast.add("Sulęcin");
    wykazMiast.add("Sulmierzyce");
    wykazMiast.add("Sułkowice");
    wykazMiast.add("Supraśl");
    wykazMiast.add("Suraż");
    wykazMiast.add("Susz");
    wykazMiast.add("Suwałki");
    wykazMiast.add("Swarzędz");
    wykazMiast.add("Syców");
    wykazMiast.add("Szadek");
    wykazMiast.add("Szamocin");
    wykazMiast.add("Szamotuły");
    wykazMiast.add("Szczawnica");
    wykazMiast.add("Szczawno Zdrój");
    wykazMiast.add("Szczebrzeszyn");
    wykazMiast.add("Szczecin");
    wykazMiast.add("Szczecinek");
    wykazMiast.add("Szczekociny");
    wykazMiast.add("Szczuczyn");
    wykazMiast.add("Szczyrk");
    wykazMiast.add("Szczytna");
    wykazMiast.add("Szczytno");
    wykazMiast.add("Szklarska Poręba");
    wykazMiast.add("Szlichtyngowa");
    wykazMiast.add("Szprotawa");
    wykazMiast.add("Sztum");
    wykazMiast.add("Szubin");
    wykazMiast.add("Szydłowiec");
    wykazMiast.add("Ścinawa");
    wykazMiast.add("Ślesin");
    wykazMiast.add("Śmigiel");
    wykazMiast.add("Śrem");
    wykazMiast.add("Środa Śląska");
    wykazMiast.add("Środa Wielkopolska");
    wykazMiast.add("Świątniki Górne");
    wykazMiast.add("Świdnica");
    wykazMiast.add("Świdnik");
    wykazMiast.add("Świdwin");
    wykazMiast.add("Świebodzice");
    wykazMiast.add("Świebodzin");
    wykazMiast.add("Świecie");
    wykazMiast.add("Świeradów Zdrój");
    wykazMiast.add("Świerzawa");
    wykazMiast.add("Świętochłowice");
    wykazMiast.add("Świnoujście");
    wykazMiast.add("Tarnobrzeg");
    wykazMiast.add("Tarnogród");
    wykazMiast.add("Tarnowskie Góry");
    wykazMiast.add("Tarnów");
    wykazMiast.add("Tczew");
    wykazMiast.add("Terespol");
    wykazMiast.add("Tłuszcz");
    wykazMiast.add("Tolkmicko");
    wykazMiast.add("Tomaszów Lubelski");
    wykazMiast.add("Tomaszów Mazowiecki");
    wykazMiast.add("Toruń");
    wykazMiast.add("Torzym");
    wykazMiast.add("Toszek");
    wykazMiast.add("Trzcianka");
    wykazMiast.add("Trzciel");
    wykazMiast.add("Trzcińsko Zdrój");
    wykazMiast.add("Trzebiatów");
    wykazMiast.add("Trzebinia");
    wykazMiast.add("Trzebnica");
    wykazMiast.add("Trzemeszno");
    wykazMiast.add("Tuchola");
    wykazMiast.add("Tuchów");
    wykazMiast.add("Tuczno");
    wykazMiast.add("Tuliszków");
    wykazMiast.add("Turek");
    wykazMiast.add("Tuszyn");
    wykazMiast.add("Twardogóra");
    wykazMiast.add("Tychy");
    wykazMiast.add("Tyczyn");
    wykazMiast.add("Tykocin");
    wykazMiast.add("Ujazd");
    wykazMiast.add("Ujście");
    wykazMiast.add("Ulanów");
    wykazMiast.add("Uniejów");
    wykazMiast.add("Ustka");
    wykazMiast.add("Ustroń");
    wykazMiast.add("Ustrzyki Dolne");
    wykazMiast.add("Wadowice");
    wykazMiast.add("Wałbrzych");
    wykazMiast.add("Wałcz");
    wykazMiast.add("Warka");
    wykazMiast.add("Warszawa");
    wykazMiast.add("Warta");
    wykazMiast.add("Wasilków");
    wykazMiast.add("Wąbrzeźno");
    wykazMiast.add("Wąchock");
    wykazMiast.add("Wągrowiec");
    wykazMiast.add("Wąsosz");
    wykazMiast.add("Wejherowo");
    wykazMiast.add("Wesoła");
    wykazMiast.add("Węgliniec");
    wykazMiast.add("Węgorzewo");
    wykazMiast.add("Węgorzyno");
    wykazMiast.add("Węgrów");
    wykazMiast.add("Wiązów");
    wykazMiast.add("Wieleń");
    wykazMiast.add("Wielichowo");
    wykazMiast.add("Wieliczka");
    wykazMiast.add("Wieluń");
    wykazMiast.add("Wieruszów");
    wykazMiast.add("Więcbork");
    wykazMiast.add("Wilamowice");
    wykazMiast.add("Wisła");
    wykazMiast.add("Witkowo");
    wykazMiast.add("Witnica");
    wykazMiast.add("Wleń");
    wykazMiast.add("Władysławowo");
    wykazMiast.add("Włocławek");
    wykazMiast.add("Włodawa");
    wykazMiast.add("Włoszczowa");
    wykazMiast.add("Wodzisław Śląski");
    wykazMiast.add("Wojcieszów");
    wykazMiast.add("Wojkowice");
    wykazMiast.add("Wolbrom");
    wykazMiast.add("Wolin");
    wykazMiast.add("Wolsztyn");
    wykazMiast.add("Wołczyn");
    wykazMiast.add("Wołomin");
    wykazMiast.add("Wołów");
    wykazMiast.add("Woźniki");
    wykazMiast.add("Wrocław");
    wykazMiast.add("Wronki");
    wykazMiast.add("Września");
    wykazMiast.add("Wschowa");
    wykazMiast.add("Wyrzysk");
    wykazMiast.add("Wysoka");
    wykazMiast.add("Wysokie Mazowieckie");
    wykazMiast.add("Wyszków");
    wykazMiast.add("Wyszogród");
    wykazMiast.add("Wyśmierzyce");
    wykazMiast.add("Zabłudów");
    wykazMiast.add("Zabrze");
    wykazMiast.add("Zagórów");
    wykazMiast.add("Zagórz");
    wykazMiast.add("Zakopane");
    wykazMiast.add("Zakroczym");
    wykazMiast.add("Zalewo");
    wykazMiast.add("Zambrów");
    wykazMiast.add("Zamość");
    wykazMiast.add("Zator");
    wykazMiast.add("Zawadzkie");
    wykazMiast.add("Zawichost");
    wykazMiast.add("Zawidów");
    wykazMiast.add("Zawiercie");
    wykazMiast.add("Ząbki");
    wykazMiast.add("Ząbkowice Śląskie");
    wykazMiast.add("Zbąszynek");
    wykazMiast.add("Zbąszyń");
    wykazMiast.add("Zduny");
    wykazMiast.add("Zduńska Wola");
    wykazMiast.add("Zdzieszowice");
    wykazMiast.add("Zelów");
    wykazMiast.add("Zgierz");
    wykazMiast.add("Zgorzelec");
    wykazMiast.add("Zielona Góra");
    wykazMiast.add("Zielonka");
    wykazMiast.add("Ziębice");
    wykazMiast.add("Złocieniec");
    wykazMiast.add("Złoczew");
    wykazMiast.add("Złotoryja");
    wykazMiast.add("Złotów");
    wykazMiast.add("Złoty Stok");
    wykazMiast.add("Zwierzyniec");
    wykazMiast.add("Zwoleń");
    wykazMiast.add("Żabno");
    wykazMiast.add("Żagań");
    wykazMiast.add("Żarki");
    wykazMiast.add("Żarów");
    wykazMiast.add("Żary");
    wykazMiast.add("Żelechów");
    wykazMiast.add("Żerków");
    wykazMiast.add("Żmigród");
    wykazMiast.add("Żnin");
    wykazMiast.add("Żory");
    wykazMiast.add("Żukowo");
    wykazMiast.add("Żuromin");
    wykazMiast.add("Żychlin");
    wykazMiast.add("Żyrardów");
    wykazMiast.add("Żywiec");
}

 public static List<String> getWykazMiast() {
     return wykazMiast;  
 }  
    private String miasto;

    public List<String> complete(String query) {  
        List<String> results = new ArrayList<String>();
        String kl = new String();
        query = query.toLowerCase(new Locale("pl"));
        for(String p : getWykazMiast()) {  
            String pl = p.toLowerCase(new Locale("pl"));
            if(pl.startsWith(query)) {
                results.add(p);
            }
        }
        return results;
    }

}
