//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.19 at 02:10:39 PM CEST 
//


package pl.gov.mf.ksef.schema.gtw.svc.types._2021._10._01._0001;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SystemCode" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}NonEmptyString32Type"/>
 *         &lt;element name="SchemaVersion" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}NonEmptyString16Type"/>
 *         &lt;element name="TargetNamespace" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}NonEmptyString256Type"/>
 *         &lt;element name="Value" type="{http://ksef.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001}NonEmptyString256Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormCodeType", propOrder = {
    "systemCode",
    "schemaVersion",
    "targetNamespace",
    "value"
})
public class FormCodeType implements Serializable {
    private static final long serialVersionUID = 1L;

    @XmlElement(name = "SystemCode", required = true)
    protected String systemCode;
    @XmlElement(name = "SchemaVersion", required = true)
    protected String schemaVersion;
    @XmlElement(name = "TargetNamespace", required = true)
    protected String targetNamespace;
    @XmlElement(name = "Value", required = true)
    protected String value;

    /**
     * Gets the value of the systemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * Sets the value of the systemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemCode(String value) {
        this.systemCode = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNamespace() {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
