//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.19 at 08:35:51 PM CEST 
//


package ksef.wysylka;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ksef.wysylka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ksef.wysylka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendInvoiceRequest }
     * 
     */
    public SendInvoiceRequest createSendInvoiceRequest() {
        return new SendInvoiceRequest();
    }

    /**
     * Create an instance of {@link SendInvoiceRequest.InvoiceHash }
     * 
     */
    public SendInvoiceRequest.InvoiceHash createSendInvoiceRequestInvoiceHash() {
        return new SendInvoiceRequest.InvoiceHash();
    }

    /**
     * Create an instance of {@link SendInvoiceRequest.InvoicePayload }
     * 
     */
    public SendInvoiceRequest.InvoicePayload createSendInvoiceRequestInvoicePayload() {
        return new SendInvoiceRequest.InvoicePayload();
    }

    /**
     * Create an instance of {@link SendInvoiceRequest.InvoiceHash.HashSHA }
     * 
     */
    public SendInvoiceRequest.InvoiceHash.HashSHA createSendInvoiceRequestInvoiceHashHashSHA() {
        return new SendInvoiceRequest.InvoiceHash.HashSHA();
    }

}
