//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.06 at 03:34:05 PM CET 
//


package sprawozdania.rok2018;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Adres uwzględniających opcjonalnie dodatkowe informacje o adresie zagranicznym organizacji
 * 
 * <p>Java class for TAdresZOpcZagranicznym complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAdresZOpcZagranicznym">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Adres" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TAdresPolski"/>
 *         &lt;element name="AdresPrzedsiebiorcyZagranicznego" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TAdresZagraniczny" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAdresZOpcZagranicznym", propOrder = {
    "adres",
    "adresPrzedsiebiorcyZagranicznego"
})
public class TAdresZOpcZagranicznym {

    @XmlElement(name = "Adres", required = true)
    protected TAdresPolski adres;
    @XmlElement(name = "AdresPrzedsiebiorcyZagranicznego")
    protected TAdresZagraniczny adresPrzedsiebiorcyZagranicznego;

    /**
     * Gets the value of the adres property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresPolski }
     *     
     */
    public TAdresPolski getAdres() {
        return adres;
    }

    /**
     * Sets the value of the adres property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresPolski }
     *     
     */
    public void setAdres(TAdresPolski value) {
        this.adres = value;
    }

    /**
     * Gets the value of the adresPrzedsiebiorcyZagranicznego property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresZagraniczny }
     *     
     */
    public TAdresZagraniczny getAdresPrzedsiebiorcyZagranicznego() {
        return adresPrzedsiebiorcyZagranicznego;
    }

    /**
     * Sets the value of the adresPrzedsiebiorcyZagranicznego property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresZagraniczny }
     *     
     */
    public void setAdresPrzedsiebiorcyZagranicznego(TAdresZagraniczny value) {
        this.adresPrzedsiebiorcyZagranicznego = value;
    }

}
