//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.29 at 12:40:48 PM CET 
//


package deklaracje.vatuek.m4;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_NBa" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2013/05/23/eD/KodyUE/}TKodKrajuUE"/>
 *           &lt;element name="P_NBb" type="{http://crd.gov.pl/wzor/2017/01/11/3845/}TNrVatUE"/>
 *           &lt;element name="P_NBc">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC">
 *                 &lt;totalDigits value="12"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="P_NBd" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1_2"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="P_NJa" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2013/05/23/eD/KodyUE/}TKodKrajuUE"/>
 *           &lt;element name="P_NJb" type="{http://crd.gov.pl/wzor/2017/01/11/3845/}TNrVatUE"/>
 *           &lt;element name="P_NJc">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TKwotaC">
 *                 &lt;totalDigits value="12"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="P_NJd" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/}TWybor1_2"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pnBa",
    "pnBb",
    "pnBc",
    "pnBd",
    "pnJa",
    "pnJb",
    "pnJc",
    "pnJd"
})
@XmlRootElement(name = "Grupa2", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
public class Grupa2 {

    @XmlElement(name = "P_NBa", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    @XmlSchemaType(name = "NMTOKEN")
    protected TKodKrajuUE pnBa;
    @XmlElement(name = "P_NBb", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    protected String pnBb;
    @XmlElement(name = "P_NBc", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    protected BigInteger pnBc;
    @XmlElement(name = "P_NBd", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    protected Byte pnBd;
    @XmlElement(name = "P_NJa", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    @XmlSchemaType(name = "NMTOKEN")
    protected TKodKrajuUE pnJa;
    @XmlElement(name = "P_NJb", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    protected String pnJb;
    @XmlElement(name = "P_NJc", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    protected BigInteger pnJc;
    @XmlElement(name = "P_NJd", namespace = "http://crd.gov.pl/wzor/2017/01/11/3845/")
    protected Byte pnJd;

    /**
     * Gets the value of the pnBa property.
     * 
     * @return
     *     possible object is
     *     {@link TKodKrajuUE }
     *     
     */
    public TKodKrajuUE getPNBa() {
        return pnBa;
    }

    /**
     * Sets the value of the pnBa property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodKrajuUE }
     *     
     */
    public void setPNBa(TKodKrajuUE value) {
        this.pnBa = value;
    }

    /**
     * Gets the value of the pnBb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNBb() {
        return pnBb;
    }

    /**
     * Sets the value of the pnBb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNBb(String value) {
        this.pnBb = value;
    }

    /**
     * Gets the value of the pnBc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPNBc() {
        return pnBc;
    }

    /**
     * Sets the value of the pnBc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPNBc(BigInteger value) {
        this.pnBc = value;
    }

    /**
     * Gets the value of the pnBd property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPNBd() {
        return pnBd;
    }

    /**
     * Sets the value of the pnBd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPNBd(Byte value) {
        this.pnBd = value;
    }

    /**
     * Gets the value of the pnJa property.
     * 
     * @return
     *     possible object is
     *     {@link TKodKrajuUE }
     *     
     */
    public TKodKrajuUE getPNJa() {
        return pnJa;
    }

    /**
     * Sets the value of the pnJa property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodKrajuUE }
     *     
     */
    public void setPNJa(TKodKrajuUE value) {
        this.pnJa = value;
    }

    /**
     * Gets the value of the pnJb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNJb() {
        return pnJb;
    }

    /**
     * Sets the value of the pnJb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNJb(String value) {
        this.pnJb = value;
    }

    /**
     * Gets the value of the pnJc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPNJc() {
        return pnJc;
    }

    /**
     * Sets the value of the pnJc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPNJc(BigInteger value) {
        this.pnJc = value;
    }

    /**
     * Gets the value of the pnJd property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPNJd() {
        return pnJd;
    }

    /**
     * Sets the value of the pnJd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPNJd(Byte value) {
        this.pnJd = value;
    }

}
